import pg from "pg";

const { Pool } = pg;

const AUTH_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS player_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id varchar(64) NOT NULL,
    guest_id varchar(128) NULL,
    login_name varchar(64) NULL,
    display_name varchar(64) NULL,
    account_type varchar(32) NOT NULL DEFAULT 'guest',
    status varchar(32) NOT NULL DEFAULT 'active',
    ban_expires_at timestamptz NULL,
    password_algo varchar(32) NULL,
    password_salt varchar(128) NULL,
    password_hash char(128) NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    last_login_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT uk_player_accounts_player_id UNIQUE (player_id),
    CONSTRAINT uk_player_accounts_guest_id UNIQUE (guest_id),
    CONSTRAINT uk_player_accounts_login_name UNIQUE (login_name)
  )`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS login_name varchar(64) NULL`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS display_name varchar(64) NULL`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS ban_expires_at timestamptz NULL`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS password_algo varchar(32) NULL`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS password_salt varchar(128) NULL`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS password_hash char(128) NULL`,
  `CREATE INDEX IF NOT EXISTS idx_player_accounts_last_login_at ON player_accounts (last_login_at)`,
  `CREATE TABLE IF NOT EXISTS auth_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id varchar(64) NULL,
    guest_id varchar(128) NULL,
    event_type varchar(32) NOT NULL,
    access_token_hash char(64) NULL,
    ticket_hash char(64) NULL,
    client_ip varchar(64) NULL,
    details_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_player_id ON auth_audit_logs (player_id)`,
  `CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_guest_id ON auth_audit_logs (guest_id)`,
  `CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_event_type ON auth_audit_logs (event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_created_at ON auth_audit_logs (created_at)`,
  `CREATE TABLE IF NOT EXISTS security_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(64) NOT NULL,
    target_type varchar(32) NULL,
    target_value varchar(256) NULL,
    client_ip varchar(64) NULL,
    severity varchar(16) NOT NULL DEFAULT 'warning',
    details_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type ON security_audit_logs (event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target ON security_audit_logs (target_type, target_value)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_client_ip ON security_audit_logs (client_ip)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_severity ON security_audit_logs (severity)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at ON security_audit_logs (created_at)`
];

function createPoolOptions(config) {
  return {
    connectionString: config.databaseUrl,
    max: config.dbPoolSize || 10
  };
}

function createGamePoolOptions(config) {
  return {
    connectionString: config.gameDatabaseUrl,
    max: config.gameDbPoolSize || config.dbPoolSize || 10
  };
}

export async function createDbPool(config) {
  if (!config.dbEnabled) {
    return null;
  }

  const pool = new Pool(createPoolOptions(config));

  let client = null;
  try {
    client = await pool.connect();
    await client.query("SELECT 1");

    for (const statement of AUTH_SCHEMA_STATEMENTS) {
      await client.query(statement);
    }
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}

export async function createGameDbPool(config) {
  if (!config.dbEnabled) {
    return null;
  }

  const pool = new Pool(createGamePoolOptions(config));

  let client = null;
  try {
    client = await pool.connect();
    await client.query("SELECT 1");
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}
