ALTER TABLE player_accounts
  ADD COLUMN IF NOT EXISTS current_world_id bigint NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_player_accounts_current_world_id
  ON player_accounts (current_world_id);

CREATE TABLE IF NOT EXISTS id_origins (
  origin_id smallint PRIMARY KEY CHECK (origin_id >= 0 AND origin_id <= 1023),
  origin_key varchar(64) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS worlds (
  world_id bigint PRIMARY KEY CHECK (world_id >= 0),
  world_key varchar(64) NOT NULL UNIQUE,
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS world_origin_memberships (
  world_id bigint NOT NULL REFERENCES worlds(world_id),
  origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  joined_at timestamptz NOT NULL DEFAULT current_timestamp,
  left_at timestamptz NULL,
  PRIMARY KEY (world_id, origin_id, joined_at)
);

CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_origin_id
  ON world_origin_memberships (origin_id);
CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_joined_at
  ON world_origin_memberships (joined_at);

CREATE TABLE IF NOT EXISTS world_merge_events (
  merge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_world_id bigint NOT NULL REFERENCES worlds(world_id),
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  source_world_ids bigint[] NOT NULL,
  source_origin_ids smallint[] NOT NULL,
  merged_at timestamptz NOT NULL DEFAULT current_timestamp,
  operator varchar(64) NULL,
  details_json jsonb NULL
);

CREATE INDEX IF NOT EXISTS idx_world_merge_events_target_world_id
  ON world_merge_events (target_world_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_active_origin_id
  ON world_merge_events (active_origin_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_merged_at
  ON world_merge_events (merged_at);

INSERT INTO id_origins (origin_id, origin_key, metadata_json)
VALUES (0, 'local-dev', '{"type":"local"}'::jsonb)
ON CONFLICT (origin_id) DO NOTHING;

INSERT INTO worlds (world_id, world_key, active_origin_id, metadata_json)
VALUES (0, 'local-dev', 0, '{"type":"local"}'::jsonb)
ON CONFLICT (world_id) DO NOTHING;

INSERT INTO world_origin_memberships (world_id, origin_id, joined_at)
SELECT 0, 0, current_timestamp
WHERE NOT EXISTS (
  SELECT 1 FROM world_origin_memberships WHERE world_id = 0 AND origin_id = 0
);
