import pg from "pg";

const { Pool } = pg;

const ANNOUNCEMENT_SCHEMA_STATEMENTS = [
  `CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
   RETURNS trigger AS $$
   BEGIN
     NEW.updated_at = current_timestamp;
     RETURN NEW;
   END;
   $$ LANGUAGE plpgsql`,
  `CREATE TABLE IF NOT EXISTS announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announce_id varchar(64) NOT NULL,
    locale varchar(32) NOT NULL DEFAULT 'default',
    title varchar(256) NOT NULL,
    content text NOT NULL,
    priority integer NOT NULL DEFAULT 0,
    announce_type varchar(32) NOT NULL DEFAULT 'banner',
    target_group varchar(128) NOT NULL DEFAULT 'all',
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT uk_announcements_announce_id UNIQUE (announce_id)
  )`,
  `ALTER TABLE announcements ADD COLUMN IF NOT EXISTS locale varchar(32) NOT NULL DEFAULT 'default'`,
  `ALTER TABLE announcements ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0`,
  `ALTER TABLE announcements ADD COLUMN IF NOT EXISTS announce_type varchar(32) NOT NULL DEFAULT 'banner'`,
  `ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_group varchar(128) NOT NULL DEFAULT 'all'`,
  `ALTER TABLE announcements ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT current_timestamp`,
  `CREATE INDEX IF NOT EXISTS idx_announcements_locale ON announcements (locale)`,
  `CREATE INDEX IF NOT EXISTS idx_announcements_priority ON announcements (priority)`,
  `CREATE INDEX IF NOT EXISTS idx_announcements_time ON announcements (start_time, end_time)`,
  `DROP TRIGGER IF EXISTS trg_announcements_updated_at ON announcements`,
  `CREATE TRIGGER trg_announcements_updated_at
     BEFORE UPDATE ON announcements
     FOR EACH ROW
     EXECUTE FUNCTION set_current_timestamp_updated_at()`
];

function createPoolOptions(config) {
  return {
    connectionString: config.databaseUrl,
    max: config.dbPoolSize,
    application_name: config.serviceName || "announce-service"
  };
}

export async function createDbPool(config) {
  if (!config.dbEnabled) {
    return null;
  }

  const pool = new Pool(createPoolOptions(config));
  let client = null;

  try {
    client = await pool.connect();
    await client.query("SELECT 1");

    for (const statement of ANNOUNCEMENT_SCHEMA_STATEMENTS) {
      await client.query(statement);
    }
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}
