export const ANNOUNCE_CONFIG = Symbol("ANNOUNCE_CONFIG");
export const ANNOUNCE_REDIS = Symbol("ANNOUNCE_REDIS");
export const ANNOUNCE_NATS = Symbol("ANNOUNCE_NATS");
export const ANNOUNCE_MYSQL_POOL = Symbol("ANNOUNCE_MYSQL_POOL");
export const ANNOUNCE_STORE = Symbol("ANNOUNCE_STORE");
export const ANNOUNCE_REGISTRY = Symbol("ANNOUNCE_REGISTRY");
export const ANNOUNCE_METRICS = Symbol("ANNOUNCE_METRICS");
