use serde_json::Value;
use sqlx::postgres::{PgPool, PgPoolOptions};

use crate::config::Config;

const AUDIT_SCHEMA_STATEMENTS: &[&str] = &[
    r#"CREATE TABLE IF NOT EXISTS game_connection_audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id bigint NOT NULL CHECK (session_id >= 0),
        player_id varchar(64) NULL,
        account_player_id varchar(64) NULL,
        character_id varchar(64) NULL,
        peer_addr varchar(128) NULL,
        event_type varchar(32) NOT NULL,
        details_json jsonb NULL,
        created_at timestamptz NOT NULL DEFAULT current_timestamp
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_player_id ON game_connection_audit_logs (player_id)",
    "CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_account_player_id ON game_connection_audit_logs (account_player_id)",
    "CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_character_id ON game_connection_audit_logs (character_id)",
    "CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_event_type ON game_connection_audit_logs (event_type)",
    "CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_created_at ON game_connection_audit_logs (created_at)",
    r#"CREATE TABLE IF NOT EXISTS room_event_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        room_id varchar(64) NOT NULL,
        player_id varchar(64) NULL,
        account_player_id varchar(64) NULL,
        character_id varchar(64) NULL,
        owner_player_id varchar(64) NULL,
        event_type varchar(32) NOT NULL,
        room_state varchar(32) NULL,
        member_count integer NOT NULL DEFAULT 0 CHECK (member_count >= 0),
        details_json jsonb NULL,
        created_at timestamptz NOT NULL DEFAULT current_timestamp
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_id ON room_event_logs (room_id)",
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_player_id ON room_event_logs (player_id)",
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_account_player_id ON room_event_logs (account_player_id)",
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_character_id ON room_event_logs (character_id)",
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_event_type ON room_event_logs (event_type)",
    "CREATE INDEX IF NOT EXISTS idx_room_event_logs_created_at ON room_event_logs (created_at)",
];

#[derive(Clone)]
pub struct PgAuditStore {
    pool: Option<PgPool>,
}

impl PgAuditStore {
    pub async fn new(config: &Config) -> Result<Self, Box<dyn std::error::Error>> {
        if !config.db_enabled {
            return Ok(Self { pool: None });
        }

        let pool = PgPoolOptions::new()
            .max_connections(config.db_pool_size.max(1))
            .connect(&config.database_url)
            .await?;

        if let Err(error) = initialize_schema(&pool).await {
            pool.close().await;
            return Err(Box::new(error));
        }

        Ok(Self { pool: Some(pool) })
    }

    pub fn enabled(&self) -> bool {
        self.pool.is_some()
    }

    pub async fn close(&self) {
        if let Some(pool) = &self.pool {
            pool.close().await;
        }
    }

    pub async fn append_connection_event(
        &self,
        session_id: u64,
        player_id: Option<&str>,
        peer_addr: Option<&str>,
        event_type: &str,
        details: Option<Value>,
    ) {
        self.append_connection_event_with_identity(
            session_id, player_id, player_id, None, peer_addr, event_type, details,
        )
        .await;
    }

    pub async fn append_connection_event_with_identity(
        &self,
        session_id: u64,
        player_id: Option<&str>,
        account_player_id: Option<&str>,
        character_id: Option<&str>,
        peer_addr: Option<&str>,
        event_type: &str,
        details: Option<Value>,
    ) {
        let Some(pool) = &self.pool else {
            return;
        };

        let session_id = i64::try_from(session_id).unwrap_or(i64::MAX);
        let _ = sqlx::query(
            r#"INSERT INTO game_connection_audit_logs (
                session_id,
                player_id,
                account_player_id,
                character_id,
                peer_addr,
                event_type,
                details_json,
                created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, current_timestamp)"#,
        )
        .bind(session_id)
        .bind(player_id)
        .bind(account_player_id)
        .bind(character_id)
        .bind(peer_addr)
        .bind(event_type)
        .bind(details)
        .execute(pool)
        .await;
    }

    pub async fn append_room_event(
        &self,
        room_id: &str,
        player_id: Option<&str>,
        owner_player_id: Option<&str>,
        event_type: &str,
        room_state: Option<&str>,
        member_count: usize,
        details: Option<Value>,
    ) {
        self.append_room_event_with_identity(
            room_id,
            player_id,
            player_id,
            None,
            owner_player_id,
            event_type,
            room_state,
            member_count,
            details,
        )
        .await;
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn append_room_event_with_identity(
        &self,
        room_id: &str,
        player_id: Option<&str>,
        account_player_id: Option<&str>,
        character_id: Option<&str>,
        owner_player_id: Option<&str>,
        event_type: &str,
        room_state: Option<&str>,
        member_count: usize,
        details: Option<Value>,
    ) {
        let Some(pool) = &self.pool else {
            return;
        };

        let member_count = i32::try_from(member_count).unwrap_or(i32::MAX);
        let _ = sqlx::query(
            r#"INSERT INTO room_event_logs (
                room_id,
                player_id,
                account_player_id,
                character_id,
                owner_player_id,
                event_type,
                room_state,
                member_count,
                details_json,
                created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, current_timestamp)"#,
        )
        .bind(room_id)
        .bind(player_id)
        .bind(account_player_id)
        .bind(character_id)
        .bind(owner_player_id)
        .bind(event_type)
        .bind(room_state)
        .bind(member_count)
        .bind(details)
        .execute(pool)
        .await;
    }

    /// Find the room_id where a player is currently offline.
    /// Returns the most recent room_id where the player had a 'member_disconnected' event
    /// but no subsequent 'player_reconnected' or 'room_left' event.
    pub async fn find_room_by_offline_player(&self, player_id: &str) -> Option<String> {
        let Some(pool) = &self.pool else {
            return None;
        };

        sqlx::query_scalar::<_, String>(
            r#"SELECT room_id FROM room_event_logs
               WHERE player_id = $1 AND event_type = 'member_disconnected'
               AND id > COALESCE(
                   (SELECT MAX(id) FROM room_event_logs
                    WHERE player_id = $2 AND event_type IN ('player_reconnected', 'room_left', 'room_disbanded')),
                   0
               )
               ORDER BY id DESC LIMIT 1"#,
        )
        .bind(player_id)
        .bind(player_id)
        .fetch_optional(pool)
        .await
        .ok()
        .flatten()
    }
}

async fn initialize_schema(pool: &PgPool) -> Result<(), sqlx::Error> {
    sqlx::query("SELECT 1").execute(pool).await?;

    for statement in AUDIT_SCHEMA_STATEMENTS {
        sqlx::query(statement).execute(pool).await?;
    }

    Ok(())
}
