-- Logical owner: auth-http
-- Compatibility phase: expand
-- Irreversible risk: none
-- Transaction: required
-- Lock timeout: 5s
-- Statement timeout: 60s
-- Backup point: not-required
-- Recovery command: stop control-plane writers, then remove only unreferenced authorization-policy objects in a reviewed follow-up migration.
-- admin-api is the control-plane consumer; auth-http remains the auth database's migration owner.
-- The old admin_accounts.role column remains temporarily for the code cutover. It is
-- not an authorization source for the new policy model and is removed in the later
-- contract migration once every management route uses AdminPolicyService.

CREATE OR REPLACE FUNCTION admin_policy_scope_is_valid(scope jsonb)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  scope_key text;
BEGIN
  IF jsonb_typeof(scope) <> 'object' THEN
    RETURN false;
  END IF;

  IF scope - ARRAY[
    'world_ids', 'service_names', 'instance_ids', 'field_allowlist',
    'target_types', 'target_ids', 'max_targets'
  ] <> '{}'::jsonb THEN
    RETURN false;
  END IF;

  FOREACH scope_key IN ARRAY ARRAY[
    'world_ids', 'service_names', 'instance_ids', 'field_allowlist',
    'target_types', 'target_ids'
  ] LOOP
    IF NOT scope ? scope_key
       OR jsonb_typeof(scope -> scope_key) <> 'array'
       OR jsonb_array_length(scope -> scope_key) = 0
       OR EXISTS (
         SELECT 1
         FROM jsonb_array_elements(scope -> scope_key) AS entry(value)
         WHERE jsonb_typeof(entry.value) <> 'string'
            OR btrim(entry.value #>> '{}') = ''
            OR char_length(entry.value #>> '{}') > 256
            OR (entry.value #>> '{}') ~ '[[:cntrl:]]'
       )
       OR (
         (scope -> scope_key) ? '*'
         AND jsonb_array_length(scope -> scope_key) <> 1
       ) THEN
      RETURN false;
    END IF;
  END LOOP;

  RETURN scope ? 'max_targets'
    AND jsonb_typeof(scope -> 'max_targets') = 'number'
    AND (scope ->> 'max_targets') ~ '^[1-9][0-9]{0,4}$'
    AND (scope ->> 'max_targets')::integer <= 10000;
END;
$$;

CREATE TABLE IF NOT EXISTS admin_permissions (
  permission_key varchar(128) PRIMARY KEY,
  resource varchar(64) NOT NULL,
  action varchar(64) NOT NULL,
  risk_level varchar(16) NOT NULL,
  scope_dimensions text[] NOT NULL DEFAULT '{}',
  description varchar(256) NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_admin_permissions_key CHECK (permission_key ~ '^[a-z][a-z0-9]*(?:[._][a-z0-9]+)*$'),
  CONSTRAINT ck_admin_permissions_resource CHECK (resource ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT ck_admin_permissions_action CHECK (action ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT ck_admin_permissions_risk CHECK (risk_level IN ('low', 'medium', 'high', 'emergency')),
  CONSTRAINT ck_admin_permissions_scope_dimensions CHECK (
    scope_dimensions <@ ARRAY[
      'world_ids', 'service_names', 'instance_ids', 'field_allowlist', 'target_types', 'target_ids'
    ]::text[]
  )
);

CREATE INDEX IF NOT EXISTS idx_admin_permissions_active
  ON admin_permissions (active, permission_key);

CREATE TABLE IF NOT EXISTS admin_roles (
  role_key varchar(64) PRIMARY KEY,
  display_name varchar(128) NOT NULL,
  description varchar(256) NOT NULL,
  builtin boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_admin_roles_key CHECK (role_key ~ '^[a-z][a-z0-9_]{0,63}$')
);

CREATE TABLE IF NOT EXISTS admin_role_permissions (
  role_key varchar(64) NOT NULL REFERENCES admin_roles(role_key),
  permission_key varchar(128) NOT NULL REFERENCES admin_permissions(permission_key),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (role_key, permission_key)
);

CREATE INDEX IF NOT EXISTS idx_admin_role_permissions_permission
  ON admin_role_permissions (permission_key, role_key);

CREATE TABLE IF NOT EXISTS admin_account_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL REFERENCES admin_accounts(id),
  role_key varchar(64) NOT NULL REFERENCES admin_roles(role_key),
  scope_json jsonb NOT NULL,
  granted_by_admin_id bigint NULL REFERENCES admin_accounts(id),
  granted_by_subject varchar(128) NOT NULL,
  reason varchar(512) NOT NULL,
  effective_at timestamptz NOT NULL DEFAULT current_timestamp,
  expires_at timestamptz NULL,
  revoked_at timestamptz NULL,
  revoked_by_admin_id bigint NULL REFERENCES admin_accounts(id),
  revoked_by_subject varchar(128) NULL,
  revocation_reason varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_admin_account_roles_scope CHECK (admin_policy_scope_is_valid(scope_json)),
  CONSTRAINT ck_admin_account_roles_reason CHECK (btrim(reason) <> ''),
  CONSTRAINT ck_admin_account_roles_grantor CHECK (btrim(granted_by_subject) <> ''),
  CONSTRAINT ck_admin_account_roles_expiry CHECK (expires_at IS NULL OR expires_at > effective_at),
  CONSTRAINT ck_admin_account_roles_revocation CHECK (
    (revoked_at IS NULL AND revoked_by_admin_id IS NULL AND revoked_by_subject IS NULL AND revocation_reason IS NULL)
    OR
    (revoked_at IS NOT NULL AND revoked_by_subject IS NOT NULL AND btrim(revoked_by_subject) <> ''
      AND revocation_reason IS NOT NULL AND btrim(revocation_reason) <> '')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_account_roles_active
  ON admin_account_roles (admin_id, role_key)
  WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_admin_account_roles_effective
  ON admin_account_roles (admin_id, effective_at, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS admin_permission_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL REFERENCES admin_accounts(id),
  permission_key varchar(128) NOT NULL REFERENCES admin_permissions(permission_key),
  scope_json jsonb NOT NULL,
  granted_by_admin_id bigint NULL REFERENCES admin_accounts(id),
  granted_by_subject varchar(128) NOT NULL,
  reason varchar(512) NOT NULL,
  effective_at timestamptz NOT NULL DEFAULT current_timestamp,
  expires_at timestamptz NULL,
  revoked_at timestamptz NULL,
  revoked_by_admin_id bigint NULL REFERENCES admin_accounts(id),
  revoked_by_subject varchar(128) NULL,
  revocation_reason varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_admin_permission_grants_scope CHECK (admin_policy_scope_is_valid(scope_json)),
  CONSTRAINT ck_admin_permission_grants_reason CHECK (btrim(reason) <> ''),
  CONSTRAINT ck_admin_permission_grants_grantor CHECK (btrim(granted_by_subject) <> ''),
  CONSTRAINT ck_admin_permission_grants_expiry CHECK (expires_at IS NULL OR expires_at > effective_at),
  CONSTRAINT ck_admin_permission_grants_revocation CHECK (
    (revoked_at IS NULL AND revoked_by_admin_id IS NULL AND revoked_by_subject IS NULL AND revocation_reason IS NULL)
    OR
    (revoked_at IS NOT NULL AND revoked_by_subject IS NOT NULL AND btrim(revoked_by_subject) <> ''
      AND revocation_reason IS NOT NULL AND btrim(revocation_reason) <> '')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_permission_grants_active
  ON admin_permission_grants (admin_id, permission_key)
  WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_admin_permission_grants_effective
  ON admin_permission_grants (admin_id, effective_at, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS admin_authorization_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(64) NOT NULL,
  actor_admin_id bigint NULL REFERENCES admin_accounts(id),
  actor_subject varchar(128) NOT NULL,
  subject_admin_id bigint NULL REFERENCES admin_accounts(id),
  role_key varchar(64) NULL REFERENCES admin_roles(role_key),
  permission_key varchar(128) NULL REFERENCES admin_permissions(permission_key),
  assignment_id bigint NULL REFERENCES admin_account_roles(id),
  grant_id bigint NULL REFERENCES admin_permission_grants(id),
  reason varchar(512) NOT NULL,
  scope_json jsonb NULL,
  details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_admin_authorization_audit_event CHECK (event_type IN (
    'account_role_granted', 'account_role_revoked', 'permission_granted', 'permission_revoked',
    'role_permission_granted', 'role_permission_revoked'
  )),
  CONSTRAINT ck_admin_authorization_audit_actor CHECK (btrim(actor_subject) <> ''),
  CONSTRAINT ck_admin_authorization_audit_reason CHECK (btrim(reason) <> ''),
  CONSTRAINT ck_admin_authorization_audit_scope CHECK (scope_json IS NULL OR admin_policy_scope_is_valid(scope_json)),
  CONSTRAINT ck_admin_authorization_audit_details CHECK (jsonb_typeof(details_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_admin_authorization_audit_subject
  ON admin_authorization_audit_events (subject_admin_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_authorization_audit_actor
  ON admin_authorization_audit_events (actor_admin_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_authorization_audit_permission
  ON admin_authorization_audit_events (permission_key, created_at DESC);

CREATE OR REPLACE FUNCTION reject_admin_authorization_audit_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'admin_authorization_audit_events is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_authorization_audit_immutable ON admin_authorization_audit_events;
CREATE TRIGGER trg_admin_authorization_audit_immutable
  BEFORE UPDATE OR DELETE ON admin_authorization_audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_admin_authorization_audit_mutation();

DROP TRIGGER IF EXISTS trg_admin_authorization_audit_no_truncate ON admin_authorization_audit_events;
CREATE TRIGGER trg_admin_authorization_audit_no_truncate
  BEFORE TRUNCATE ON admin_authorization_audit_events
  FOR EACH STATEMENT EXECUTE FUNCTION reject_admin_authorization_audit_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON admin_authorization_audit_events FROM PUBLIC;

INSERT INTO admin_permissions (
  permission_key, resource, action, risk_level, scope_dimensions, description
) VALUES
  ('audit.read', 'audit', 'read', 'low', '{}', 'Read management audit records'),
  ('assets.ledger.read', 'asset_ledger', 'read', 'low', ARRAY['target_ids'], 'Read player asset ledger records'),
  ('security.read', 'security', 'read', 'low', '{}', 'Read control-plane security events'),
  ('players.read', 'players', 'read', 'low', ARRAY['target_ids'], 'Read player records'),
  ('players.status.update', 'players', 'update_status', 'medium', ARRAY['target_ids'], 'Update non-ban player status'),
  ('players.ban', 'players', 'ban', 'high', ARRAY['target_ids'], 'Apply player ban status'),
  ('gm.broadcast', 'gm', 'broadcast', 'high', ARRAY['world_ids'], 'Send a world-scoped broadcast'),
  ('gm.send_item', 'gm', 'send_item', 'high', ARRAY['world_ids', 'target_ids'], 'Grant an item to one or more players'),
  ('gm.asset_correction.emergency', 'gm', 'asset_correction', 'emergency', ARRAY['world_ids', 'target_ids'], 'Apply emergency asset correction'),
  ('gm.kick_player', 'gm', 'kick_player', 'high', ARRAY['target_ids'], 'Disconnect selected players'),
  ('gm.ban_player', 'gm', 'ban_player', 'high', ARRAY['target_ids'], 'Ban selected players'),
  ('gm.character_elements.write', 'character', 'write_elements', 'medium', ARRAY['world_ids', 'target_ids', 'field_allowlist'], 'Change character element values'),
  ('gm.character_titles.write', 'character', 'write_titles', 'medium', ARRAY['world_ids', 'target_ids'], 'Change character titles'),
  ('gm.character_disciplines.write', 'character', 'write_disciplines', 'medium', ARRAY['world_ids', 'target_ids'], 'Change character disciplines'),
  ('maintenance.read', 'maintenance', 'read', 'low', ARRAY['service_names'], 'Read maintenance state'),
  ('maintenance.write', 'maintenance', 'write', 'high', ARRAY['service_names'], 'Change maintenance state'),
  ('monitoring.read', 'monitoring', 'read', 'low', ARRAY['service_names'], 'Read monitoring snapshots'),
  ('monitoring.archive', 'monitoring', 'archive', 'medium', ARRAY['service_names'], 'Archive monitoring snapshots'),
  ('id.read', 'global_id', 'read', 'low', '{}', 'Decode and inspect global IDs'),
  ('id.manage', 'global_id', 'manage', 'high', ARRAY['world_ids'], 'Manage global ID origins and worlds'),
  ('myforge.agent.read', 'myforge_agent', 'read', 'low', ARRAY['service_names'], 'Read MyForge agent state'),
  ('myforge.task.read', 'myforge_task', 'read', 'low', ARRAY['service_names'], 'Read MyForge task state'),
  ('myforge.task.create', 'myforge_task', 'create', 'high', ARRAY['service_names', 'target_ids'], 'Create a controlled MyForge task'),
  ('myforge.task.cancel', 'myforge_task', 'cancel', 'medium', ARRAY['service_names', 'target_ids'], 'Cancel a MyForge task'),
  ('admins.revoke_tokens', 'admin_account', 'revoke_tokens', 'high', ARRAY['target_ids'], 'Revoke an administrator session set'),
  ('admins.reset_password', 'admin_account', 'reset_password', 'high', ARRAY['target_ids'], 'Reset an administrator password'),
  ('admin.permissions.manage', 'admin_permission', 'manage', 'emergency', ARRAY['target_ids'], 'Grant or revoke control-plane permissions'),
  ('breakglass.activate', 'breakglass', 'activate', 'emergency', ARRAY['service_names', 'target_ids'], 'Activate a short-lived emergency authorization'),
  ('game.config.write', 'game_config', 'write', 'high', ARRAY['world_ids', 'service_names'], 'Reload or activate game configuration'),
  ('game.room.transfer', 'room', 'transfer', 'high', ARRAY['world_ids', 'instance_ids', 'target_ids'], 'Transfer a Room between game instances'),
  ('proxy.maintenance.write', 'proxy_maintenance', 'write', 'high', ARRAY['service_names', 'instance_ids'], 'Change proxy maintenance behavior'),
  ('proxy.rollout.write', 'proxy_rollout', 'write', 'high', ARRAY['service_names', 'instance_ids'], 'Start or control proxy rollout'),
  ('proxy.route.write', 'proxy_route', 'write', 'high', ARRAY['service_names', 'instance_ids', 'target_ids'], 'Change proxy routing')
ON CONFLICT (permission_key) DO UPDATE
SET resource = EXCLUDED.resource,
    action = EXCLUDED.action,
    risk_level = EXCLUDED.risk_level,
    scope_dimensions = EXCLUDED.scope_dimensions,
    description = EXCLUDED.description,
    active = true,
    updated_at = current_timestamp;

INSERT INTO admin_roles (role_key, display_name, description, builtin)
VALUES
  ('viewer', 'Viewer', 'Read-only control-plane access', true),
  ('operator', 'Operator', 'Scoped operational and reversible player actions', true),
  ('admin', 'Administrator', 'Broad control-plane actions except emergency permissions', true),
  ('super_admin', 'Super administrator', 'Full control-plane access including emergency permissions', true)
ON CONFLICT (role_key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    builtin = true,
    active = true,
    updated_at = current_timestamp;

INSERT INTO admin_role_permissions (role_key, permission_key)
SELECT 'viewer', permission_key
FROM admin_permissions
WHERE permission_key IN (
  'audit.read', 'security.read', 'players.read', 'maintenance.read', 'monitoring.read', 'id.read'
)
ON CONFLICT DO NOTHING;

INSERT INTO admin_role_permissions (role_key, permission_key)
SELECT 'operator', permission_key
FROM admin_permissions
WHERE permission_key IN (
  'audit.read', 'security.read', 'players.read', 'players.status.update', 'maintenance.read',
  'monitoring.read', 'id.read', 'gm.broadcast', 'gm.send_item', 'gm.kick_player',
  'gm.character_elements.write', 'gm.character_titles.write', 'gm.character_disciplines.write'
)
ON CONFLICT DO NOTHING;

INSERT INTO admin_role_permissions (role_key, permission_key)
SELECT 'admin', permission_key
FROM admin_permissions
WHERE permission_key NOT IN (
  'gm.asset_correction.emergency', 'admin.permissions.manage', 'breakglass.activate'
)
ON CONFLICT DO NOTHING;

INSERT INTO admin_role_permissions (role_key, permission_key)
SELECT 'super_admin', permission_key
FROM admin_permissions
ON CONFLICT DO NOTHING;

COMMENT ON COLUMN admin_accounts.role IS
  'Legacy compatibility column. New control-plane authorization uses admin_account_roles and admin_permission_grants.';
