-- Logical owner: auth-http
-- Compatibility phase: expand
-- Irreversible risk: none for a new empty database; initialized databases must use the catalog baseline workflow.
-- Baseline schema extracted from db/init.sql. This file contains schema only; development data belongs in db/seeds/development.
CREATE TABLE IF NOT EXISTS player_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NOT NULL,
  current_world_id bigint NOT NULL DEFAULT 0,
  guest_id varchar(128) NULL,
  login_name varchar(64) NULL,
  display_name varchar(64) NULL,
  account_type varchar(32) NOT NULL DEFAULT 'guest',
  status varchar(32) NOT NULL DEFAULT 'active',
  ban_expires_at timestamptz NULL,
  password_algo varchar(32) NULL,
  password_salt varchar(128) NULL,
  password_hash char(128) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_accounts_player_id UNIQUE (player_id),
  CONSTRAINT uk_player_accounts_guest_id UNIQUE (guest_id),
  CONSTRAINT uk_player_accounts_login_name UNIQUE (login_name)
);

CREATE INDEX IF NOT EXISTS idx_player_accounts_current_world_id
  ON player_accounts (current_world_id);
CREATE INDEX IF NOT EXISTS idx_player_accounts_last_login_at
  ON player_accounts (last_login_at);

CREATE TABLE IF NOT EXISTS auth_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NULL,
  guest_id varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  access_token_hash char(64) NULL,
  ticket_hash char(64) NULL,
  client_ip varchar(64) NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_player_id
  ON auth_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_guest_id
  ON auth_audit_logs (guest_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_event_type
  ON auth_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_created_at
  ON auth_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS security_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  client_ip varchar(64) NULL,
  severity varchar(16) NOT NULL DEFAULT 'warning',
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN security_audit_logs.target_type IS 'ip, account, ticket, etc.';
COMMENT ON COLUMN security_audit_logs.target_value IS 'ip address, login_name, etc.';
COMMENT ON COLUMN security_audit_logs.severity IS 'info, warning, critical';

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type
  ON security_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target
  ON security_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_client_ip
  ON security_audit_logs (client_ip);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_severity
  ON security_audit_logs (severity);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at
  ON security_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(64) NOT NULL,
  display_name varchar(64) NULL,
  password_algo varchar(32) NOT NULL DEFAULT 'scrypt',
  password_salt varchar(128) NOT NULL,
  password_hash varchar(256) NOT NULL,
  role varchar(32) NOT NULL DEFAULT 'viewer',
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NULL,
  CONSTRAINT uk_admin_accounts_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_admin_accounts_role
  ON admin_accounts (role);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_status
  ON admin_accounts (status);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NULL,
  admin_username varchar(64) NULL,
  action varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  details_json jsonb NULL,
  ip varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id
  ON admin_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action
  ON admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
  ON admin_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
  ON admin_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS myforge_agents (
  agent_id varchar(128) PRIMARY KEY,
  project_id varchar(128) NOT NULL,
  label varchar(128) NULL,
  public_key_fingerprint varchar(64) NOT NULL,
  configured boolean NOT NULL DEFAULT true,
  status varchar(32) NOT NULL DEFAULT 'offline',
  hostname varchar(255) NULL,
  platform varchar(32) NULL,
  agent_version varchar(64) NULL,
  forge_root_summary_json jsonb NULL,
  capabilities_json jsonb NULL,
  limits_json jsonb NULL,
  effective_limits_json jsonb NULL,
  connection_id uuid NULL,
  last_registered_at timestamptz NULL,
  connected_at timestamptz NULL,
  last_seen_at timestamptz NULL,
  disconnected_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_myforge_agents_agent_id CHECK (agent_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  CONSTRAINT ck_myforge_agents_project_id CHECK (project_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  CONSTRAINT ck_myforge_agents_fingerprint CHECK (public_key_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_agents_status CHECK (status IN ('online', 'offline')),
  CONSTRAINT ck_myforge_agents_connection_status CHECK ((status = 'online') = (connection_id IS NOT NULL)),
  CONSTRAINT ck_myforge_agents_root_summary CHECK (forge_root_summary_json IS NULL OR jsonb_typeof(forge_root_summary_json) = 'object'),
  CONSTRAINT ck_myforge_agents_capabilities CHECK (capabilities_json IS NULL OR jsonb_typeof(capabilities_json) = 'object'),
  CONSTRAINT ck_myforge_agents_limits CHECK (limits_json IS NULL OR jsonb_typeof(limits_json) = 'object'),
  CONSTRAINT ck_myforge_agents_effective_limits CHECK (effective_limits_json IS NULL OR jsonb_typeof(effective_limits_json) = 'object')
);

ALTER TABLE myforge_agents
  ADD COLUMN IF NOT EXISTS connection_id uuid NULL;

CREATE INDEX IF NOT EXISTS idx_myforge_agents_configured_status
  ON myforge_agents (configured, status, agent_id);
CREATE INDEX IF NOT EXISTS idx_myforge_agents_project_id
  ON myforge_agents (project_id, agent_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_myforge_agents_connection_id
  ON myforge_agents (connection_id)
  WHERE connection_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS myforge_task_runs (
  request_id uuid PRIMARY KEY,
  task_type varchar(64) NOT NULL,
  project_id varchar(128) NOT NULL,
  agent_id varchar(128) NOT NULL,
  status varchar(32) NOT NULL,
  queue_reason varchar(32) NULL,
  execution_mode varchar(32) NULL,
  danger_full_access boolean NULL,
  connection_id uuid NULL,
  artifact_file varchar(512) NOT NULL,
  consumer_target_file varchar(512) NULL,
  rules_file varchar(512) NULL,
  prompt_json jsonb NOT NULL,
  rendered_prompt text NOT NULL,
  command_preview text NOT NULL,
  command_digest varchar(64) NULL,
  command_expires_at timestamptz NULL,
  timeout_ms integer NOT NULL,
  max_output_bytes integer NOT NULL,
  stdout_preview text NULL,
  stderr_preview text NULL,
  stdout_bytes bigint NULL,
  stderr_bytes bigint NULL,
  stdout_truncated boolean NOT NULL DEFAULT false,
  stderr_truncated boolean NOT NULL DEFAULT false,
  exit_code integer NULL,
  artifact_json jsonb NULL,
  audit_json jsonb NULL,
  result_digest varchar(64) NULL,
  error_code varchar(64) NULL,
  error_message text NULL,
  created_by_admin_id bigint NULL,
  created_by_admin_username varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  queue_expires_at timestamptz NOT NULL,
  dispatched_at timestamptz NULL,
  started_at timestamptz NULL,
  cancel_requested_at timestamptz NULL,
  cancel_deadline_at timestamptz NULL,
  completed_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_myforge_tasks_type CHECK (task_type = 'fangyuan.blueprint.generate'),
  CONSTRAINT ck_myforge_tasks_status CHECK (status IN ('queued', 'dispatched', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled')),
  CONSTRAINT ck_myforge_tasks_queue_reason CHECK (queue_reason IS NULL OR queue_reason IN ('agent_offline', 'agent_busy')),
  CONSTRAINT ck_myforge_tasks_queue_reason_status CHECK (queue_reason IS NULL OR status = 'queued'),
  CONSTRAINT ck_myforge_tasks_execution_mode CHECK (execution_mode IS NULL OR execution_mode IN ('codex_exec', 'dry_run')),
  CONSTRAINT ck_myforge_tasks_danger_access CHECK ((execution_mode IS NULL) = (danger_full_access IS NULL)),
  CONSTRAINT ck_myforge_tasks_prompt_json CHECK (jsonb_typeof(prompt_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_artifact_json CHECK (artifact_json IS NULL OR jsonb_typeof(artifact_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_audit_json CHECK (audit_json IS NULL OR jsonb_typeof(audit_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_error_code CHECK (error_code IS NULL OR error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT ck_myforge_tasks_timeout CHECK (timeout_ms BETWEEN 1000 AND 1800000),
  CONSTRAINT ck_myforge_tasks_max_output CHECK (max_output_bytes BETWEEN 4096 AND 4194304),
  CONSTRAINT ck_myforge_tasks_stdout_bytes CHECK (stdout_bytes IS NULL OR stdout_bytes >= 0),
  CONSTRAINT ck_myforge_tasks_stderr_bytes CHECK (stderr_bytes IS NULL OR stderr_bytes >= 0),
  CONSTRAINT ck_myforge_tasks_command_digest CHECK (command_digest IS NULL OR command_digest ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_tasks_result_digest CHECK (result_digest IS NULL OR result_digest ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_tasks_cancel_pair CHECK ((cancel_requested_at IS NULL) = (cancel_deadline_at IS NULL)),
  CONSTRAINT ck_myforge_tasks_cancel_order CHECK (cancel_deadline_at IS NULL OR cancel_deadline_at >= cancel_requested_at),
  CONSTRAINT ck_myforge_tasks_queue_expiry CHECK (queue_expires_at >= created_at),
  CONSTRAINT ck_myforge_tasks_completion CHECK ((status IN ('completed', 'completed_with_errors', 'failed', 'cancelled')) = (completed_at IS NOT NULL)),
  CONSTRAINT ck_myforge_tasks_dispatch_fields CHECK (
    (connection_id IS NULL AND execution_mode IS NULL AND command_digest IS NULL AND command_expires_at IS NULL AND dispatched_at IS NULL)
    OR
    (connection_id IS NOT NULL AND execution_mode IS NOT NULL AND command_digest IS NOT NULL AND command_expires_at IS NOT NULL AND dispatched_at IS NOT NULL)
  )
);

ALTER TABLE myforge_task_runs
  ALTER COLUMN rules_file DROP NOT NULL;

ALTER TABLE myforge_task_runs
  ADD COLUMN IF NOT EXISTS danger_full_access boolean NULL;

UPDATE myforge_task_runs
SET danger_full_access = false
WHERE execution_mode IS NOT NULL AND danger_full_access IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'ck_myforge_tasks_danger_access'
      AND conrelid = 'myforge_task_runs'::regclass
  ) THEN
    ALTER TABLE myforge_task_runs
      ADD CONSTRAINT ck_myforge_tasks_danger_access
      CHECK ((execution_mode IS NULL) = (danger_full_access IS NULL));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_myforge_tasks_agent_status_created
  ON myforge_task_runs (agent_id, status, created_at, request_id);
CREATE INDEX IF NOT EXISTS idx_myforge_tasks_project_created
  ON myforge_task_runs (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_myforge_tasks_created_at
  ON myforge_task_runs (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_myforge_tasks_agent_active
  ON myforge_task_runs (agent_id)
  WHERE status IN ('dispatched', 'running');

CREATE TABLE IF NOT EXISTS id_origins (
  origin_id smallint PRIMARY KEY CHECK (origin_id >= 0 AND origin_id <= 1023),
  origin_key varchar(64) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS worlds (
  world_id bigint PRIMARY KEY CHECK (world_id >= 0),
  world_key varchar(64) NOT NULL UNIQUE,
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS world_origin_memberships (
  world_id bigint NOT NULL REFERENCES worlds(world_id),
  origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  joined_at timestamptz NOT NULL DEFAULT current_timestamp,
  left_at timestamptz NULL,
  PRIMARY KEY (world_id, origin_id, joined_at)
);

CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_origin_id
  ON world_origin_memberships (origin_id);
CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_joined_at
  ON world_origin_memberships (joined_at);

CREATE TABLE IF NOT EXISTS world_merge_events (
  merge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_world_id bigint NOT NULL REFERENCES worlds(world_id),
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  source_world_ids bigint[] NOT NULL,
  source_origin_ids smallint[] NOT NULL,
  merged_at timestamptz NOT NULL DEFAULT current_timestamp,
  operator varchar(64) NULL,
  details_json jsonb NULL
);

CREATE INDEX IF NOT EXISTS idx_world_merge_events_target_world_id
  ON world_merge_events (target_world_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_active_origin_id
  ON world_merge_events (active_origin_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_merged_at
  ON world_merge_events (merged_at);
