-- Logical owner: auth-http
-- Compatibility phase: expand
-- Irreversible risk: none
-- Transaction: required
-- Lock timeout: 5s
-- Statement timeout: 60s
-- Backup point: not-required
-- Recovery command: SQLx rolls back the transaction; correct the migration and rerun db up.

-- This table used to be created by admin-api at startup. Keep the existing
-- production rows intact while moving the schema under migration control.
CREATE TABLE IF NOT EXISTS metrics_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name varchar(64) NOT NULL,
  bucket_time integer NOT NULL CHECK (bucket_time >= 0),
  qps integer NOT NULL DEFAULT 0 CHECK (qps >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  online_value integer NOT NULL DEFAULT 0 CHECK (online_value >= 0),
  extra jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_metrics_archive_service_time
  ON metrics_archive (service_name, bucket_time);
CREATE UNIQUE INDEX IF NOT EXISTS uk_metrics_archive_service_time
  ON metrics_archive (service_name, bucket_time);

CREATE INDEX IF NOT EXISTS idx_worlds_active_origin_id
  ON worlds (active_origin_id);
CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_origin
  ON world_origin_memberships (origin_id, joined_at, left_at);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_target_world
  ON world_merge_events (target_world_id, merged_at);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_active_origin
  ON world_merge_events (active_origin_id, merged_at);
