import pg from "pg";

const { Pool } = pg;

const MAIL_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS mails (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_id varchar(64) NOT NULL,
    sender_type varchar(32) NOT NULL DEFAULT 'system',
    sender_id varchar(64) NOT NULL,
    sender_name varchar(128) NULL,
    from_player_id varchar(64) NOT NULL,
    to_player_id varchar(64) NOT NULL,
    title varchar(256) NOT NULL,
    content text NULL,
    attachments jsonb NULL,
    mail_type varchar(32) NOT NULL DEFAULT 'system',
    created_by_type varchar(32) NOT NULL DEFAULT 'system',
    created_by_id varchar(64) NULL,
    created_by_name varchar(128) NULL,
    status varchar(32) NOT NULL DEFAULT 'unread',
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    read_at timestamptz NULL,
    claimed_at timestamptz NULL,
    expires_at timestamptz NULL,
    CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mails_to_player_id ON mails (to_player_id)`,
  `CREATE INDEX IF NOT EXISTS idx_mails_status ON mails (to_player_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_mails_created_at ON mails (created_at)`,
  `CREATE TABLE IF NOT EXISTS mail_notification_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_id varchar(64) NOT NULL,
    to_player_id varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    status varchar(32) NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at timestamptz NULL DEFAULT current_timestamp,
    locked_until timestamptz NULL,
    last_error varchar(512) NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    sent_at timestamptz NULL,
    CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
    CONSTRAINT fk_mail_notification_outbox_mail_id
      FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
      ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
     ON mail_notification_outbox (status, next_attempt_at, id)`,
  `CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
     ON mail_notification_outbox (to_player_id)`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS sender_type varchar(32) NOT NULL DEFAULT 'system'`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS sender_id varchar(64) NOT NULL DEFAULT 'system'`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS sender_name varchar(128) NULL`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS created_by_type varchar(32) NOT NULL DEFAULT 'system'`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS created_by_id varchar(64) NULL`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS created_by_name varchar(128) NULL`,
  `ALTER TABLE mails ADD COLUMN IF NOT EXISTS claimed_at timestamptz NULL`,
  `UPDATE mails
   SET sender_type = CASE
         WHEN LOWER(COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')) = 'system' THEN 'system'
         ELSE 'player'
       END,
       sender_id = CASE
         WHEN LOWER(COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')) = 'system' THEN 'system'
         ELSE COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')
       END,
       sender_name = CASE
         WHEN COALESCE(NULLIF(sender_name, ''), '') <> '' THEN sender_name
         WHEN LOWER(COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')) = 'system' THEN '系统'
         ELSE COALESCE(NULLIF(sender_id, ''), from_player_id)
       END,
       created_by_type = COALESCE(NULLIF(created_by_type, ''), CASE
         WHEN LOWER(COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')) = 'system' THEN 'system'
         ELSE 'player'
       END),
       created_by_id = COALESCE(NULLIF(created_by_id, ''), COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')),
       created_by_name = CASE
         WHEN COALESCE(NULLIF(created_by_name, ''), '') <> '' THEN created_by_name
         WHEN COALESCE(NULLIF(sender_name, ''), '') <> '' THEN sender_name
         WHEN LOWER(COALESCE(NULLIF(sender_id, ''), from_player_id, 'system')) = 'system' THEN '系统'
         ELSE COALESCE(NULLIF(sender_id, ''), from_player_id)
       END`
];

function createPoolOptions(config) {
  return {
    connectionString: config.databaseUrl,
    max: config.dbPoolSize,
    application_name: config.serviceName || "mail-service"
  };
}

export async function createDbPool(config) {
  if (!config.dbEnabled) {
    return null;
  }

  const pool = new Pool(createPoolOptions(config));

  let client = null;
  try {
    client = await pool.connect();
    await client.query("SELECT 1");

    for (const statement of MAIL_SCHEMA_STATEMENTS) {
      await client.query(statement);
    }
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}
