-- Announce Service Database Schema
-- Database: myserver_announce

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announce_id varchar(64) NOT NULL,
  locale varchar(32) NOT NULL DEFAULT 'default',
  title varchar(256) NOT NULL,
  content text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  announce_type varchar(32) NOT NULL DEFAULT 'banner',
  target_group varchar(128) NOT NULL DEFAULT 'all',
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_announcements_announce_id UNIQUE (announce_id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_locale
  ON announcements (locale);
CREATE INDEX IF NOT EXISTS idx_announcements_priority
  ON announcements (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_time
  ON announcements (start_time, end_time);

DROP TRIGGER IF EXISTS trg_announcements_updated_at ON announcements;
CREATE TRIGGER trg_announcements_updated_at
  BEFORE UPDATE ON announcements
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

INSERT INTO announcements (
  announce_id,
  locale,
  title,
  content,
  priority,
  announce_type,
  target_group,
  start_time,
  end_time
)
VALUES
  (
    'announce_test_001',
    'default',
    'Welcome to MyServer',
    'This is the default announcement for all players.',
    10,
    'banner',
    'all',
    current_timestamp - interval '1 hour',
    current_timestamp + interval '7 days'
  ),
  (
    'announce_test_002',
    'zh-CN',
    '版本维护通知',
    '今晚 20:00 开始进行版本维护，请提前下线。',
    20,
    'popup',
    'all',
    current_timestamp - interval '30 minutes',
    current_timestamp + interval '1 day'
  )
ON CONFLICT (announce_id) DO NOTHING;
