-- Logical owner: chat-server
-- Compatibility phase: expand
-- Irreversible risk: none for a new empty database; initialized databases must use the catalog baseline workflow.
-- Baseline schema extracted from db/init.sql. This file contains schema only; development data belongs in db/seeds/development.
CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msg_id varchar(64) NOT NULL,
  chat_type smallint NOT NULL,
  sender_id varchar(64) NOT NULL,
  content text NOT NULL,
  created_at bigint NOT NULL,
  target_id varchar(64) NULL,
  group_id varchar(64) NULL,
  CONSTRAINT uk_chat_messages_msg_id UNIQUE (msg_id)
);

CREATE INDEX IF NOT EXISTS idx_sender
  ON chat_messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_target
  ON chat_messages (target_id);
CREATE INDEX IF NOT EXISTS idx_group
  ON chat_messages (group_id);
CREATE INDEX IF NOT EXISTS idx_created
  ON chat_messages (created_at);

CREATE TABLE IF NOT EXISTS chat_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  name varchar(128) NOT NULL,
  owner_id varchar(64) NOT NULL,
  created_at bigint NOT NULL,
  CONSTRAINT uk_chat_groups_group_id UNIQUE (group_id)
);

CREATE INDEX IF NOT EXISTS idx_owner
  ON chat_groups (owner_id);

CREATE TABLE IF NOT EXISTS chat_group_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  player_id varchar(64) NOT NULL,
  joined_at bigint NOT NULL,
  CONSTRAINT uk_group_player UNIQUE (group_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_player
  ON chat_group_members (player_id);
