// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthReq {
    #[prost(string, tag = "1")]
    pub ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingReq {
    #[prost(int64, tag = "1")]
    pub client_time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRes {
    #[prost(int64, tag = "1")]
    pub server_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinReq {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub policy_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomLeaveReq {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomLeaveRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomReadyReq {
    #[prost(bool, tag = "1")]
    pub ready: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomReadyRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ready: bool,
    #[prost(string, tag = "4")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomStartReq {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomStartRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInputReq {
    #[prost(uint32, tag = "1")]
    pub frame_id: u32,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInputRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MoveInputReq {
    #[prost(uint32, tag = "1")]
    pub frame_id: u32,
    #[prost(enumeration = "MoveInputType", tag = "2")]
    pub input_type: i32,
    #[prost(float, tag = "3")]
    pub dir_x: f32,
    #[prost(float, tag = "4")]
    pub dir_y: f32,
    #[prost(bool, tag = "5")]
    pub has_client_state: bool,
    #[prost(float, tag = "6")]
    pub client_x: f32,
    #[prost(float, tag = "7")]
    pub client_y: f32,
    #[prost(uint32, tag = "8")]
    pub client_frame_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveInputRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetRoomDataReq {
    #[prost(int32, tag = "1")]
    pub id_start: i32,
    #[prost(int32, tag = "2")]
    pub id_end: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoomDataRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, repeated, tag = "2")]
    pub field_0_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameInput {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payload_json: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub frame_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameBundlePush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub frame_id: u32,
    #[prost(uint32, tag = "3")]
    pub fps: u32,
    #[prost(message, repeated, tag = "4")]
    pub inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(bool, tag = "5")]
    pub is_silent_frame: bool,
    #[prost(message, optional, tag = "6")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomFrameRatePush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub fps: u32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameMessagePush {
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomEndReq {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomEndRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomMember {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ready: bool,
    #[prost(bool, tag = "3")]
    pub is_owner: bool,
    #[prost(bool, tag = "4")]
    pub offline: bool,
    #[prost(enumeration = "MemberRole", tag = "5")]
    pub role: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomSnapshot {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner_player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub members: ::prost::alloc::vec::Vec<RoomMember>,
    #[prost(uint32, tag = "5")]
    pub current_frame_id: u32,
    #[prost(string, tag = "6")]
    pub game_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityTransform {
    #[prost(uint64, tag = "1")]
    pub entity_id: u64,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub scene_id: i32,
    #[prost(float, tag = "4")]
    pub x: f32,
    #[prost(float, tag = "5")]
    pub y: f32,
    #[prost(float, tag = "6")]
    pub dir_x: f32,
    #[prost(float, tag = "7")]
    pub dir_y: f32,
    #[prost(bool, tag = "8")]
    pub moving: bool,
    #[prost(uint32, tag = "9")]
    pub last_input_frame: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomStatePush {
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MovementSnapshotPush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub frame_id: u32,
    #[prost(message, repeated, tag = "3")]
    pub entities: ::prost::alloc::vec::Vec<EntityTransform>,
    #[prost(bool, tag = "4")]
    pub full_sync: bool,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    #[prost(enumeration = "MovementCorrectionKind", tag = "6")]
    pub correction_kind: i32,
    #[prost(enumeration = "MovementCorrectionReason", tag = "7")]
    pub reason_code: i32,
    #[prost(string, repeated, tag = "8")]
    pub target_player_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "9")]
    pub reference_frame_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MovementRejectPush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub frame_id: u32,
    #[prost(string, tag = "3")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub corrected: ::core::option::Option<EntityTransform>,
    #[prost(enumeration = "MovementCorrectionKind", tag = "6")]
    pub correction_kind: i32,
    #[prost(enumeration = "MovementCorrectionReason", tag = "7")]
    pub reason_code: i32,
    #[prost(uint32, tag = "8")]
    pub reference_frame_id: u32,
    #[prost(bool, tag = "9")]
    pub has_client_state: bool,
    #[prost(float, tag = "10")]
    pub client_x: f32,
    #[prost(float, tag = "11")]
    pub client_y: f32,
    #[prost(float, tag = "12")]
    pub server_x: f32,
    #[prost(float, tag = "13")]
    pub server_y: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MovementRecoveryState {
    #[prost(uint32, tag = "1")]
    pub frame_id: u32,
    #[prost(message, repeated, tag = "2")]
    pub entities: ::prost::alloc::vec::Vec<EntityTransform>,
    #[prost(enumeration = "MovementCorrectionKind", tag = "3")]
    pub correction_kind: i32,
    #[prost(enumeration = "MovementCorrectionReason", tag = "4")]
    pub reason_code: i32,
    #[prost(uint32, tag = "5")]
    pub reference_frame_id: u32,
    #[prost(bool, tag = "6")]
    pub aoi_enabled: bool,
    #[prost(float, tag = "7")]
    pub aoi_radius: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinAsObserverReq {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinAsObserverRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
    #[prost(uint32, tag = "5")]
    pub current_frame_id: u32,
    #[prost(message, repeated, tag = "6")]
    pub recent_inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(uint32, tag = "7")]
    pub waiting_frame_id: u32,
    #[prost(message, repeated, tag = "8")]
    pub waiting_inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(uint32, tag = "9")]
    pub input_delay_frames: u32,
    #[prost(message, optional, tag = "10")]
    pub movement_recovery: ::core::option::Option<MovementRecoveryState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomReconnectReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomReconnectRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
    #[prost(uint32, tag = "5")]
    pub current_frame_id: u32,
    #[prost(message, repeated, tag = "6")]
    pub recent_inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(uint32, tag = "7")]
    pub waiting_frame_id: u32,
    #[prost(message, repeated, tag = "8")]
    pub waiting_inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(uint32, tag = "9")]
    pub input_delay_frames: u32,
    #[prost(message, optional, tag = "10")]
    pub movement_recovery: ::core::option::Option<MovementRecoveryState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomMemberOfflinePush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub offline: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateMatchedRoomReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub player_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateMatchedRoomRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorRes {
    #[prost(string, tag = "1")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Item {
    #[prost(uint64, tag = "1")]
    pub uid: u64,
    #[prost(int32, tag = "2")]
    pub item_id: i32,
    #[prost(uint32, tag = "3")]
    pub count: u32,
    #[prost(bool, tag = "4")]
    pub binded: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AttrPanel {
    #[prost(int64, tag = "1")]
    pub hp: i64,
    #[prost(int64, tag = "2")]
    pub max_hp: i64,
    #[prost(int64, tag = "3")]
    pub attack: i64,
    #[prost(int64, tag = "4")]
    pub defense: i64,
    #[prost(int32, tag = "5")]
    pub speed: i32,
    #[prost(float, tag = "6")]
    pub crit_rate: f32,
    #[prost(float, tag = "7")]
    pub crit_dmg: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttrRecord {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub attr_type: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub value: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemEquipReq {
    #[prost(uint64, tag = "1")]
    pub item_uid: u64,
    #[prost(string, tag = "2")]
    pub equip_slot: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemEquipRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub unequipped_item: ::core::option::Option<Item>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemUseReq {
    #[prost(uint64, tag = "1")]
    pub item_uid: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemUseRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub hp_change: i64,
    #[prost(int32, repeated, tag = "4")]
    pub new_buff_ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemDiscardReq {
    #[prost(uint64, tag = "1")]
    pub item_uid: u64,
    #[prost(uint32, tag = "2")]
    pub count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemDiscardRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemAddReq {
    #[prost(int32, tag = "1")]
    pub item_id: i32,
    #[prost(uint32, tag = "2")]
    pub count: u32,
    #[prost(bool, tag = "3")]
    pub binded: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemAddRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub item: ::core::option::Option<Item>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WarehouseAccessReq {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub item_uid: u64,
    #[prost(uint32, tag = "3")]
    pub count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WarehouseAccessRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetInventoryReq {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInventoryRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub inventory_items: ::prost::alloc::vec::Vec<Item>,
    #[prost(message, repeated, tag = "4")]
    pub warehouse_items: ::prost::alloc::vec::Vec<Item>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryUpdatePush {
    #[prost(message, repeated, tag = "1")]
    pub inventory_items: ::prost::alloc::vec::Vec<Item>,
    #[prost(message, repeated, tag = "2")]
    pub warehouse_items: ::prost::alloc::vec::Vec<Item>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttrChangePush {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<AttrPanel>,
    #[prost(message, repeated, tag = "2")]
    pub bonus: ::prost::alloc::vec::Vec<AttrRecord>,
    #[prost(message, optional, tag = "3")]
    pub r#final: ::core::option::Option<AttrPanel>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VisualChangePush {
    #[prost(uint32, tag = "1")]
    pub appearance: u32,
    #[prost(int32, repeated, tag = "2")]
    pub active_buff_ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemObtainPush {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Item>,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemberRole {
    Player = 0,
    Observer = 1,
}
impl MemberRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Player => "MEMBER_ROLE_PLAYER",
            Self::Observer => "MEMBER_ROLE_OBSERVER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEMBER_ROLE_PLAYER" => Some(Self::Player),
            "MEMBER_ROLE_OBSERVER" => Some(Self::Observer),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MoveInputType {
    Unknown = 0,
    MoveDir = 1,
    MoveStop = 2,
    FaceTo = 3,
}
impl MoveInputType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "MOVE_INPUT_TYPE_UNKNOWN",
            Self::MoveDir => "MOVE_INPUT_TYPE_MOVE_DIR",
            Self::MoveStop => "MOVE_INPUT_TYPE_MOVE_STOP",
            Self::FaceTo => "MOVE_INPUT_TYPE_FACE_TO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOVE_INPUT_TYPE_UNKNOWN" => Some(Self::Unknown),
            "MOVE_INPUT_TYPE_MOVE_DIR" => Some(Self::MoveDir),
            "MOVE_INPUT_TYPE_MOVE_STOP" => Some(Self::MoveStop),
            "MOVE_INPUT_TYPE_FACE_TO" => Some(Self::FaceTo),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MovementCorrectionKind {
    Incremental = 0,
    FullSync = 1,
    Strong = 2,
    Recovery = 3,
}
impl MovementCorrectionKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Incremental => "MOVEMENT_CORRECTION_KIND_INCREMENTAL",
            Self::FullSync => "MOVEMENT_CORRECTION_KIND_FULL_SYNC",
            Self::Strong => "MOVEMENT_CORRECTION_KIND_STRONG",
            Self::Recovery => "MOVEMENT_CORRECTION_KIND_RECOVERY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOVEMENT_CORRECTION_KIND_INCREMENTAL" => Some(Self::Incremental),
            "MOVEMENT_CORRECTION_KIND_FULL_SYNC" => Some(Self::FullSync),
            "MOVEMENT_CORRECTION_KIND_STRONG" => Some(Self::Strong),
            "MOVEMENT_CORRECTION_KIND_RECOVERY" => Some(Self::Recovery),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MovementCorrectionReason {
    Unknown = 0,
    Periodic = 1,
    ClientDrift = 2,
    MovementRejected = 3,
    CollisionBlocked = 4,
    GameStarted = 5,
    ReconnectRecovery = 6,
    ObserverRecovery = 7,
}
impl MovementCorrectionReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "MOVEMENT_CORRECTION_REASON_UNKNOWN",
            Self::Periodic => "MOVEMENT_CORRECTION_REASON_PERIODIC",
            Self::ClientDrift => "MOVEMENT_CORRECTION_REASON_CLIENT_DRIFT",
            Self::MovementRejected => "MOVEMENT_CORRECTION_REASON_MOVEMENT_REJECTED",
            Self::CollisionBlocked => "MOVEMENT_CORRECTION_REASON_COLLISION_BLOCKED",
            Self::GameStarted => "MOVEMENT_CORRECTION_REASON_GAME_STARTED",
            Self::ReconnectRecovery => "MOVEMENT_CORRECTION_REASON_RECONNECT_RECOVERY",
            Self::ObserverRecovery => "MOVEMENT_CORRECTION_REASON_OBSERVER_RECOVERY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOVEMENT_CORRECTION_REASON_UNKNOWN" => Some(Self::Unknown),
            "MOVEMENT_CORRECTION_REASON_PERIODIC" => Some(Self::Periodic),
            "MOVEMENT_CORRECTION_REASON_CLIENT_DRIFT" => Some(Self::ClientDrift),
            "MOVEMENT_CORRECTION_REASON_MOVEMENT_REJECTED" => {
                Some(Self::MovementRejected)
            }
            "MOVEMENT_CORRECTION_REASON_COLLISION_BLOCKED" => {
                Some(Self::CollisionBlocked)
            }
            "MOVEMENT_CORRECTION_REASON_GAME_STARTED" => Some(Self::GameStarted),
            "MOVEMENT_CORRECTION_REASON_RECONNECT_RECOVERY" => {
                Some(Self::ReconnectRecovery)
            }
            "MOVEMENT_CORRECTION_REASON_OBSERVER_RECOVERY" => {
                Some(Self::ObserverRecovery)
            }
            _ => None,
        }
    }
}
