// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthReq {
    #[prost(string, tag = "1")]
    pub ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingReq {
    #[prost(int64, tag = "1")]
    pub client_time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRes {
    #[prost(int64, tag = "1")]
    pub server_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinReq {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomJoinRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomLeaveReq {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomLeaveRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomReadyReq {
    #[prost(bool, tag = "1")]
    pub ready: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomReadyRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ready: bool,
    #[prost(string, tag = "4")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoomStartReq {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomStartRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInputReq {
    #[prost(uint32, tag = "1")]
    pub frame_id: u32,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInputRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetRoomDataReq {
    #[prost(int32, tag = "1")]
    pub id_start: i32,
    #[prost(int32, tag = "2")]
    pub id_end: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoomDataRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, repeated, tag = "2")]
    pub field_0_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameInput {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameBundlePush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub frame_id: u32,
    #[prost(uint32, tag = "3")]
    pub fps: u32,
    #[prost(message, repeated, tag = "4")]
    pub inputs: ::prost::alloc::vec::Vec<FrameInput>,
    #[prost(bool, tag = "5")]
    pub is_silent_frame: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomFrameRatePush {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub fps: u32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameMessagePush {
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub payload_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomEndReq {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomEndRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomMember {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ready: bool,
    #[prost(bool, tag = "3")]
    pub is_owner: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomSnapshot {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner_player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub members: ::prost::alloc::vec::Vec<RoomMember>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomStatePush {
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub snapshot: ::core::option::Option<RoomSnapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorRes {
    #[prost(string, tag = "1")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
