use serde::{Deserialize, Serialize};
use sqlx::{PgPool, Row, postgres::PgPoolOptions};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatMessage {
    pub msg_id: String,
    pub chat_type: i32, // 1=私聊, 2=群聊
    pub sender_id: String,
    pub content: String,
    pub created_at: i64,
    pub target_id: String, // 私聊时为对方用户ID
    pub group_id: String,  // 群聊时为群组ID
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatGroup {
    pub group_id: String,
    pub name: String,
    pub owner_id: String,
    pub created_at: i64,
}

#[derive(Clone)]
pub struct ChatStore {
    pool: Option<PgPool>,
}

impl ChatStore {
    pub fn disabled() -> Self {
        Self { pool: None }
    }

    pub async fn new(
        db_enabled: bool,
        database_url: &str,
        db_pool_size: u32,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        if !db_enabled {
            return Ok(Self::disabled());
        }

        let pool = PgPoolOptions::new()
            .max_connections(db_pool_size.max(1))
            .connect(database_url)
            .await?;

        sqlx::query("SELECT 1").execute(&pool).await?;

        // 创建聊天消息表
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS chat_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                msg_id VARCHAR(64) NOT NULL UNIQUE,
                chat_type SMALLINT NOT NULL,
                sender_id VARCHAR(64) NOT NULL,
                content TEXT NOT NULL,
                created_at BIGINT NOT NULL,
                target_id VARCHAR(64) NOT NULL DEFAULT '',
                group_id VARCHAR(64) NOT NULL DEFAULT ''
            )"#,
        )
        .execute(&pool)
        .await?;
        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_sender ON chat_messages (sender_id)",
        )
        .execute(&pool)
        .await?;
        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_target ON chat_messages (target_id)",
        )
        .execute(&pool)
        .await?;
        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_group ON chat_messages (group_id)",
        )
        .execute(&pool)
        .await?;
        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_created ON chat_messages (created_at)",
        )
        .execute(&pool)
        .await?;

        // 创建群组表
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS chat_groups (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_id VARCHAR(64) NOT NULL UNIQUE,
                name VARCHAR(128) NOT NULL,
                owner_id VARCHAR(64) NOT NULL,
                created_at BIGINT NOT NULL
            )"#,
        )
        .execute(&pool)
        .await?;
        sqlx::query("CREATE INDEX IF NOT EXISTS idx_chat_groups_owner ON chat_groups (owner_id)")
            .execute(&pool)
            .await?;

        // 创建群组成员表
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS chat_group_members (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_id VARCHAR(64) NOT NULL,
                player_id VARCHAR(64) NOT NULL,
                joined_at BIGINT NOT NULL,
                CONSTRAINT uk_chat_group_members_group_player UNIQUE (group_id, player_id)
            )"#,
        )
        .execute(&pool)
        .await?;
        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_chat_group_members_player ON chat_group_members (player_id)",
        )
        .execute(&pool)
        .await?;

        Ok(Self { pool: Some(pool) })
    }

    pub fn enabled(&self) -> bool {
        self.pool.is_some()
    }

    pub async fn close(&self) {
        if let Some(pool) = &self.pool {
            pool.close().await;
        }
    }

    // ============================================================
    // 消息存储
    // ============================================================

    pub async fn save_private_message(&self, msg: &ChatMessage) -> Result<(), sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(());
        };

        sqlx::query(
            r#"INSERT INTO chat_messages (
                msg_id, chat_type, sender_id, content, created_at, target_id, group_id
            ) VALUES ($1, $2, $3, $4, $5, $6, $7)"#,
        )
        .bind(&msg.msg_id)
        .bind(msg.chat_type as i16)
        .bind(&msg.sender_id)
        .bind(&msg.content)
        .bind(msg.created_at)
        .bind(&msg.target_id)
        .bind(&msg.group_id)
        .execute(pool)
        .await?;
        Ok(())
    }

    pub async fn save_group_message(&self, msg: &ChatMessage) -> Result<(), sqlx::Error> {
        self.save_private_message(msg).await
    }

    pub async fn get_private_history(
        &self,
        player_a: &str,
        player_b: &str,
        before_time: i64,
        limit: i32,
    ) -> Result<Vec<ChatMessage>, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(Vec::new());
        };

        let rows = sqlx::query(
            r#"SELECT msg_id, chat_type, sender_id, content, created_at, target_id, group_id
               FROM chat_messages
               WHERE chat_type = 1
                 AND ((sender_id = $1 AND target_id = $2) OR (sender_id = $2 AND target_id = $1))
                 AND created_at < $3
               ORDER BY created_at DESC
               LIMIT $4"#,
        )
        .bind(player_a)
        .bind(player_b)
        .bind(before_time)
        .bind(limit)
        .fetch_all(pool)
        .await?;

        Ok(rows
            .into_iter()
            .map(|row| ChatMessage {
                msg_id: row.get("msg_id"),
                chat_type: i32::from(row.get::<i16, _>("chat_type")),
                sender_id: row.get("sender_id"),
                content: row.get("content"),
                created_at: row.get("created_at"),
                target_id: row.get("target_id"),
                group_id: row.get("group_id"),
            })
            .collect())
    }

    pub async fn get_group_history(
        &self,
        group_id: &str,
        before_time: i64,
        limit: i32,
    ) -> Result<Vec<ChatMessage>, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(Vec::new());
        };

        let rows = sqlx::query(
            r#"SELECT msg_id, chat_type, sender_id, content, created_at, target_id, group_id
               FROM chat_messages
               WHERE chat_type = 2 AND group_id = $1 AND created_at < $2
               ORDER BY created_at DESC
               LIMIT $3"#,
        )
        .bind(group_id)
        .bind(before_time)
        .bind(limit)
        .fetch_all(pool)
        .await?;

        Ok(rows
            .into_iter()
            .map(|row| ChatMessage {
                msg_id: row.get("msg_id"),
                chat_type: i32::from(row.get::<i16, _>("chat_type")),
                sender_id: row.get("sender_id"),
                content: row.get("content"),
                created_at: row.get("created_at"),
                target_id: row.get("target_id"),
                group_id: row.get("group_id"),
            })
            .collect())
    }

    // ============================================================
    // 群组管理
    // ============================================================

    pub async fn create_group(&self, group: &ChatGroup) -> Result<(), sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(());
        };

        sqlx::query(
            r#"INSERT INTO chat_groups (group_id, name, owner_id, created_at)
               VALUES ($1, $2, $3, $4)"#,
        )
        .bind(&group.group_id)
        .bind(&group.name)
        .bind(&group.owner_id)
        .bind(group.created_at)
        .execute(pool)
        .await?;

        sqlx::query(
            r#"INSERT INTO chat_group_members (group_id, player_id, joined_at)
               VALUES ($1, $2, $3)
               ON CONFLICT (group_id, player_id) DO NOTHING"#,
        )
        .bind(&group.group_id)
        .bind(&group.owner_id)
        .bind(group.created_at)
        .execute(pool)
        .await?;

        Ok(())
    }

    pub async fn get_group(&self, group_id: &str) -> Result<Option<ChatGroup>, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(None);
        };

        let row = sqlx::query(
            r#"SELECT group_id, name, owner_id, created_at FROM chat_groups WHERE group_id = $1"#,
        )
        .bind(group_id)
        .fetch_optional(pool)
        .await?;

        Ok(row.map(|row| ChatGroup {
            group_id: row.get("group_id"),
            name: row.get("name"),
            owner_id: row.get("owner_id"),
            created_at: row.get("created_at"),
        }))
    }

    pub async fn delete_group(&self, group_id: &str) -> Result<(), sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(());
        };

        sqlx::query(r#"DELETE FROM chat_group_members WHERE group_id = $1"#)
            .bind(group_id)
            .execute(pool)
            .await?;

        sqlx::query(r#"DELETE FROM chat_groups WHERE group_id = $1"#)
            .bind(group_id)
            .execute(pool)
            .await?;

        Ok(())
    }

    pub async fn add_group_member(
        &self,
        group_id: &str,
        player_id: &str,
        joined_at: i64,
    ) -> Result<(), sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(());
        };

        sqlx::query(
            r#"INSERT INTO chat_group_members (group_id, player_id, joined_at)
               VALUES ($1, $2, $3)
               ON CONFLICT (group_id, player_id) DO NOTHING"#,
        )
        .bind(group_id)
        .bind(player_id)
        .bind(joined_at)
        .execute(pool)
        .await?;
        Ok(())
    }

    pub async fn remove_group_member(
        &self,
        group_id: &str,
        player_id: &str,
    ) -> Result<(), sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(());
        };

        sqlx::query(r#"DELETE FROM chat_group_members WHERE group_id = $1 AND player_id = $2"#)
            .bind(group_id)
            .bind(player_id)
            .execute(pool)
            .await?;
        Ok(())
    }

    pub async fn get_group_members(&self, group_id: &str) -> Result<Vec<String>, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(Vec::new());
        };

        let rows = sqlx::query(r#"SELECT player_id FROM chat_group_members WHERE group_id = $1"#)
            .bind(group_id)
            .fetch_all(pool)
            .await?;

        Ok(rows.into_iter().map(|row| row.get("player_id")).collect())
    }

    pub async fn get_player_groups(&self, player_id: &str) -> Result<Vec<ChatGroup>, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(Vec::new());
        };

        let rows = sqlx::query(
            r#"SELECT g.group_id, g.name, g.owner_id, g.created_at
               FROM chat_groups g
               INNER JOIN chat_group_members gm ON g.group_id = gm.group_id
               WHERE gm.player_id = $1"#,
        )
        .bind(player_id)
        .fetch_all(pool)
        .await?;

        Ok(rows
            .into_iter()
            .map(|row| ChatGroup {
                group_id: row.get("group_id"),
                name: row.get("name"),
                owner_id: row.get("owner_id"),
                created_at: row.get("created_at"),
            })
            .collect())
    }

    pub async fn get_group_member_count(&self, group_id: &str) -> Result<i32, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(0);
        };

        let count: i64 =
            sqlx::query_scalar(r#"SELECT COUNT(*) FROM chat_group_members WHERE group_id = $1"#)
                .bind(group_id)
                .fetch_one(pool)
                .await?;

        Ok(count as i32)
    }

    pub async fn is_group_owner(
        &self,
        group_id: &str,
        player_id: &str,
    ) -> Result<bool, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(false);
        };

        let count: i64 = sqlx::query_scalar(
            r#"SELECT COUNT(*) FROM chat_groups WHERE group_id = $1 AND owner_id = $2"#,
        )
        .bind(group_id)
        .bind(player_id)
        .fetch_one(pool)
        .await?;

        Ok(count > 0)
    }

    pub async fn is_group_member(
        &self,
        group_id: &str,
        player_id: &str,
    ) -> Result<bool, sqlx::Error> {
        let Some(pool) = &self.pool else {
            return Ok(false);
        };

        let count: i64 = sqlx::query_scalar(
            r#"SELECT COUNT(*) FROM chat_group_members WHERE group_id = $1 AND player_id = $2"#,
        )
        .bind(group_id)
        .bind(player_id)
        .fetch_one(pool)
        .await?;

        Ok(count > 0)
    }
}
