import pg from "pg";

const { Pool } = pg;

const ADMIN_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS player_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id varchar(64) NOT NULL,
    guest_id varchar(128) NULL,
    login_name varchar(64) NULL,
    display_name varchar(64) NULL,
    account_type varchar(32) NOT NULL DEFAULT 'guest',
    status varchar(32) NOT NULL DEFAULT 'active',
    ban_expires_at timestamptz NULL,
    password_algo varchar(32) NULL,
    password_salt varchar(128) NULL,
    password_hash char(128) NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    last_login_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT uk_player_accounts_player_id UNIQUE (player_id),
    CONSTRAINT uk_player_accounts_guest_id UNIQUE (guest_id),
    CONSTRAINT uk_player_accounts_login_name UNIQUE (login_name)
  )`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS ban_expires_at timestamptz NULL`,
  `CREATE INDEX IF NOT EXISTS idx_player_accounts_last_login_at ON player_accounts (last_login_at)`,
  `CREATE TABLE IF NOT EXISTS admin_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL,
    display_name varchar(64) NULL,
    password_algo varchar(32) NOT NULL DEFAULT 'scrypt',
    password_salt varchar(128) NOT NULL,
    password_hash varchar(256) NOT NULL,
    role varchar(32) NOT NULL DEFAULT 'viewer',
    status varchar(32) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    last_login_at timestamptz NULL,
    CONSTRAINT uk_admin_accounts_username UNIQUE (username)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_accounts_role ON admin_accounts (role)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_accounts_status ON admin_accounts (status)`,
  `CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id bigint NULL,
    admin_username varchar(64) NULL,
    action varchar(64) NOT NULL,
    target_type varchar(32) NULL,
    target_value varchar(256) NULL,
    details_json jsonb NULL,
    ip varchar(64) NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id ON admin_audit_logs (admin_id)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action ON admin_audit_logs (action)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target ON admin_audit_logs (target_type, target_value)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at ON admin_audit_logs (created_at)`,
  `CREATE TABLE IF NOT EXISTS security_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(64) NOT NULL,
    target_type varchar(32) NULL,
    target_value varchar(256) NULL,
    client_ip varchar(64) NULL,
    severity varchar(16) NOT NULL DEFAULT 'warning',
    details_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type ON security_audit_logs (event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target ON security_audit_logs (target_type, target_value)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_client_ip ON security_audit_logs (client_ip)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_severity ON security_audit_logs (severity)`,
  `CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at ON security_audit_logs (created_at)`,
  `CREATE TABLE IF NOT EXISTS metrics_archive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(64) NOT NULL,
    bucket_time integer NOT NULL CHECK (bucket_time >= 0),
    qps integer NOT NULL DEFAULT 0 CHECK (qps >= 0),
    latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
    online_value integer NOT NULL DEFAULT 0 CHECK (online_value >= 0),
    extra jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_metrics_archive_service_time ON metrics_archive (service_name, bucket_time)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uk_metrics_archive_service_time ON metrics_archive (service_name, bucket_time)`,
  `ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS current_world_id bigint NOT NULL DEFAULT 0`,
  `CREATE INDEX IF NOT EXISTS idx_player_accounts_current_world_id ON player_accounts (current_world_id)`,
  `CREATE TABLE IF NOT EXISTS id_origins (
    origin_id smallint PRIMARY KEY CHECK (origin_id >= 0 AND origin_id <= 1023),
    origin_key varchar(64) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    retired_at timestamptz NULL,
    metadata_json jsonb NULL
  )`,
  `ALTER TABLE id_origins ADD COLUMN IF NOT EXISTS metadata_json jsonb NULL`,
  `CREATE TABLE IF NOT EXISTS worlds (
    world_id bigint PRIMARY KEY CHECK (world_id >= 0),
    world_key varchar(64) NOT NULL UNIQUE,
    active_origin_id smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    retired_at timestamptz NULL,
    metadata_json jsonb NULL
  )`,
  `ALTER TABLE worlds ADD COLUMN IF NOT EXISTS metadata_json jsonb NULL`,
  `CREATE INDEX IF NOT EXISTS idx_worlds_active_origin_id ON worlds (active_origin_id)`,
  `CREATE TABLE IF NOT EXISTS world_origin_memberships (
    world_id bigint NOT NULL,
    origin_id smallint NOT NULL,
    joined_at timestamptz NOT NULL DEFAULT current_timestamp,
    left_at timestamptz NULL,
    PRIMARY KEY (world_id, origin_id, joined_at)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_origin ON world_origin_memberships (origin_id, joined_at, left_at)`,
  `CREATE TABLE IF NOT EXISTS world_merge_events (
    merge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_world_id bigint NOT NULL,
    active_origin_id smallint NOT NULL,
    source_world_ids bigint[] NOT NULL,
    source_origin_ids smallint[] NOT NULL,
    merged_at timestamptz NOT NULL DEFAULT current_timestamp,
    operator varchar(64) NULL,
    details_json jsonb NULL
  )`,
  `ALTER TABLE world_merge_events ALTER COLUMN merged_at SET DEFAULT current_timestamp`,
  `CREATE INDEX IF NOT EXISTS idx_world_merge_events_target_world ON world_merge_events (target_world_id, merged_at)`,
  `CREATE INDEX IF NOT EXISTS idx_world_merge_events_active_origin ON world_merge_events (active_origin_id, merged_at)`,
  `CREATE INDEX IF NOT EXISTS idx_world_merge_events_merged_at ON world_merge_events (merged_at)`,
  `INSERT INTO id_origins (origin_id, origin_key, metadata_json)
   VALUES (0, 'local-dev', '{"type":"local"}'::jsonb)
   ON CONFLICT (origin_id) DO NOTHING`,
  `INSERT INTO worlds (world_id, world_key, active_origin_id, metadata_json)
   VALUES (0, 'local-dev', 0, '{"type":"local"}'::jsonb)
   ON CONFLICT (world_id) DO NOTHING`,
  `INSERT INTO world_origin_memberships (world_id, origin_id, joined_at)
   SELECT 0, 0, current_timestamp
   WHERE NOT EXISTS (
     SELECT 1 FROM world_origin_memberships WHERE world_id = 0 AND origin_id = 0
   )`
];

export async function createDbPool(config) {
  const pool = new Pool({
    connectionString: config.databaseUrl,
    max: config.dbPoolSize || 10
  });

  let client = null;
  try {
    client = await pool.connect();
    await client.query("SELECT 1");
    for (const statement of ADMIN_SCHEMA_STATEMENTS) {
      await client.query(statement);
    }
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}

export async function createGameDbPool(config) {
  const pool = new Pool({
    connectionString: config.gameDatabaseUrl,
    max: config.gameDbPoolSize || config.dbPoolSize || 10
  });

  let client = null;
  try {
    client = await pool.connect();
    await client.query("SELECT 1");
  } catch (error) {
    client?.release();
    client = null;
    await pool.end();
    throw error;
  } finally {
    client?.release();
  }

  return pool;
}
