-- Logical owner: announce-service
-- Compatibility phase: expand
-- Irreversible risk: none for a new empty database; initialized databases must use the catalog baseline workflow.
-- Baseline schema extracted from db/init.sql. This file contains schema only; development data belongs in db/seeds/development.
CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announce_id varchar(64) NOT NULL,
  world_id bigint NOT NULL DEFAULT 0,
  locale varchar(32) NOT NULL DEFAULT 'default',
  title varchar(256) NOT NULL,
  content text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  announce_type varchar(32) NOT NULL DEFAULT 'banner',
  target_group varchar(128) NOT NULL DEFAULT 'all',
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_announcements_announce_id UNIQUE (announce_id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_locale
  ON announcements (locale);
CREATE INDEX IF NOT EXISTS idx_announcements_world_id
  ON announcements (world_id);
CREATE INDEX IF NOT EXISTS idx_announcements_priority
  ON announcements (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_time
  ON announcements (start_time, end_time);

DROP TRIGGER IF EXISTS trg_announcements_updated_at ON announcements;
CREATE TRIGGER trg_announcements_updated_at
  BEFORE UPDATE ON announcements
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();
