// This file is @generated by prost-build.
/// ============================================================
/// MatchStart
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStartReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    /// "1v1", "3v3", "5v5"
    #[prost(string, tag = "2")]
    pub mode: ::prost::alloc::string::String,
    /// 预留：段位（暂不使用）
    #[prost(int32, tag = "3")]
    pub rank_tier: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStartRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchCancel
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchCancelReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchCancelRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchStatus
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStatusReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStatusRes {
    /// "idle", "matching", "matched", "in_room"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    /// matched/in_room 时有效
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
    /// 进入房间的临时凭证
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
    /// 预计等待时间
    #[prost(int64, tag = "5")]
    pub estimated_wait_secs: i64,
}
/// ============================================================
/// MatchEventStream
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEventStreamReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEvent {
    /// "matched", "match_failed", "match_cancelled"
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// CreateRoomAndJoin (GameServer -> MatchService)
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoomAndJoinReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub player_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoomAndJoinRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// PlayerJoined (GameServer -> MatchService)
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerJoinedReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerJoinedRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// PlayerLeft (GameServer -> MatchService)
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerLeftReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    /// "normal", "disconnect", "kicked"
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerLeftRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// 所有人都离开，是否 abort 匹配
    #[prost(bool, tag = "2")]
    pub match_should_abort: bool,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchEnd (GameServer -> MatchService)
/// ============================================================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEndReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    /// "game_over", "aborted", "timeout"
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEndRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod match_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ============================================================
    /// MatchService 对外接口（客户端调用）
    /// ============================================================
    #[derive(Debug, Clone)]
    pub struct MatchServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MatchServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MatchServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MatchServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MatchServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 客户端发起匹配
        pub async fn match_start(
            &mut self,
            request: impl tonic::IntoRequest<super::MatchStartReq>,
        ) -> std::result::Result<tonic::Response<super::MatchStartRes>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchService/MatchStart",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("myserver.matchservice.MatchService", "MatchStart"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 客户端取消匹配
        pub async fn match_cancel(
            &mut self,
            request: impl tonic::IntoRequest<super::MatchCancelReq>,
        ) -> std::result::Result<tonic::Response<super::MatchCancelRes>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchService/MatchCancel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("myserver.matchservice.MatchService", "MatchCancel"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 客户端查询匹配状态
        pub async fn match_status(
            &mut self,
            request: impl tonic::IntoRequest<super::MatchStatusReq>,
        ) -> std::result::Result<tonic::Response<super::MatchStatusRes>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchService/MatchStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("myserver.matchservice.MatchService", "MatchStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 客户端订阅匹配事件推送
        pub async fn match_event_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::MatchEventStreamReq>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MatchEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchService/MatchEventStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "myserver.matchservice.MatchService",
                        "MatchEventStream",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod match_internal_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ============================================================
    /// MatchInternal 对内接口（GameServer 调用）
    /// ============================================================
    #[derive(Debug, Clone)]
    pub struct MatchInternalClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MatchInternalClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MatchInternalClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MatchInternalClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MatchInternalClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GameServer 创建房间成功后回调
        pub async fn create_room_and_join(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRoomAndJoinReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateRoomAndJoinRes>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchInternal/CreateRoomAndJoin",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "myserver.matchservice.MatchInternal",
                        "CreateRoomAndJoin",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GameServer 通知玩家已进入房间
        pub async fn player_joined(
            &mut self,
            request: impl tonic::IntoRequest<super::PlayerJoinedReq>,
        ) -> std::result::Result<
            tonic::Response<super::PlayerJoinedRes>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchInternal/PlayerJoined",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "myserver.matchservice.MatchInternal",
                        "PlayerJoined",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GameServer 通知玩家已离开房间
        pub async fn player_left(
            &mut self,
            request: impl tonic::IntoRequest<super::PlayerLeftReq>,
        ) -> std::result::Result<tonic::Response<super::PlayerLeftRes>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchInternal/PlayerLeft",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("myserver.matchservice.MatchInternal", "PlayerLeft"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GameServer 通知对局结束
        pub async fn match_end(
            &mut self,
            request: impl tonic::IntoRequest<super::MatchEndReq>,
        ) -> std::result::Result<tonic::Response<super::MatchEndRes>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/myserver.matchservice.MatchInternal/MatchEnd",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("myserver.matchservice.MatchInternal", "MatchEnd"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod match_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MatchServiceServer.
    #[async_trait]
    pub trait MatchService: std::marker::Send + std::marker::Sync + 'static {
        /// 客户端发起匹配
        async fn match_start(
            &self,
            request: tonic::Request<super::MatchStartReq>,
        ) -> std::result::Result<tonic::Response<super::MatchStartRes>, tonic::Status>;
        /// 客户端取消匹配
        async fn match_cancel(
            &self,
            request: tonic::Request<super::MatchCancelReq>,
        ) -> std::result::Result<tonic::Response<super::MatchCancelRes>, tonic::Status>;
        /// 客户端查询匹配状态
        async fn match_status(
            &self,
            request: tonic::Request<super::MatchStatusReq>,
        ) -> std::result::Result<tonic::Response<super::MatchStatusRes>, tonic::Status>;
        /// Server streaming response type for the MatchEventStream method.
        type MatchEventStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::MatchEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// 客户端订阅匹配事件推送
        async fn match_event_stream(
            &self,
            request: tonic::Request<super::MatchEventStreamReq>,
        ) -> std::result::Result<
            tonic::Response<Self::MatchEventStreamStream>,
            tonic::Status,
        >;
    }
    /// ============================================================
    /// MatchService 对外接口（客户端调用）
    /// ============================================================
    #[derive(Debug)]
    pub struct MatchServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MatchServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MatchServiceServer<T>
    where
        T: MatchService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/myserver.matchservice.MatchService/MatchStart" => {
                    #[allow(non_camel_case_types)]
                    struct MatchStartSvc<T: MatchService>(pub Arc<T>);
                    impl<
                        T: MatchService,
                    > tonic::server::UnaryService<super::MatchStartReq>
                    for MatchStartSvc<T> {
                        type Response = super::MatchStartRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MatchStartReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchService>::match_start(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MatchStartSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchService/MatchCancel" => {
                    #[allow(non_camel_case_types)]
                    struct MatchCancelSvc<T: MatchService>(pub Arc<T>);
                    impl<
                        T: MatchService,
                    > tonic::server::UnaryService<super::MatchCancelReq>
                    for MatchCancelSvc<T> {
                        type Response = super::MatchCancelRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MatchCancelReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchService>::match_cancel(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MatchCancelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchService/MatchStatus" => {
                    #[allow(non_camel_case_types)]
                    struct MatchStatusSvc<T: MatchService>(pub Arc<T>);
                    impl<
                        T: MatchService,
                    > tonic::server::UnaryService<super::MatchStatusReq>
                    for MatchStatusSvc<T> {
                        type Response = super::MatchStatusRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MatchStatusReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchService>::match_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MatchStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchService/MatchEventStream" => {
                    #[allow(non_camel_case_types)]
                    struct MatchEventStreamSvc<T: MatchService>(pub Arc<T>);
                    impl<
                        T: MatchService,
                    > tonic::server::ServerStreamingService<super::MatchEventStreamReq>
                    for MatchEventStreamSvc<T> {
                        type Response = super::MatchEvent;
                        type ResponseStream = T::MatchEventStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MatchEventStreamReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchService>::match_event_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MatchEventStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MatchServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "myserver.matchservice.MatchService";
    impl<T> tonic::server::NamedService for MatchServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated server implementations.
pub mod match_internal_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MatchInternalServer.
    #[async_trait]
    pub trait MatchInternal: std::marker::Send + std::marker::Sync + 'static {
        /// GameServer 创建房间成功后回调
        async fn create_room_and_join(
            &self,
            request: tonic::Request<super::CreateRoomAndJoinReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateRoomAndJoinRes>,
            tonic::Status,
        >;
        /// GameServer 通知玩家已进入房间
        async fn player_joined(
            &self,
            request: tonic::Request<super::PlayerJoinedReq>,
        ) -> std::result::Result<tonic::Response<super::PlayerJoinedRes>, tonic::Status>;
        /// GameServer 通知玩家已离开房间
        async fn player_left(
            &self,
            request: tonic::Request<super::PlayerLeftReq>,
        ) -> std::result::Result<tonic::Response<super::PlayerLeftRes>, tonic::Status>;
        /// GameServer 通知对局结束
        async fn match_end(
            &self,
            request: tonic::Request<super::MatchEndReq>,
        ) -> std::result::Result<tonic::Response<super::MatchEndRes>, tonic::Status>;
    }
    /// ============================================================
    /// MatchInternal 对内接口（GameServer 调用）
    /// ============================================================
    #[derive(Debug)]
    pub struct MatchInternalServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MatchInternalServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MatchInternalServer<T>
    where
        T: MatchInternal,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/myserver.matchservice.MatchInternal/CreateRoomAndJoin" => {
                    #[allow(non_camel_case_types)]
                    struct CreateRoomAndJoinSvc<T: MatchInternal>(pub Arc<T>);
                    impl<
                        T: MatchInternal,
                    > tonic::server::UnaryService<super::CreateRoomAndJoinReq>
                    for CreateRoomAndJoinSvc<T> {
                        type Response = super::CreateRoomAndJoinRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRoomAndJoinReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchInternal>::create_room_and_join(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateRoomAndJoinSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchInternal/PlayerJoined" => {
                    #[allow(non_camel_case_types)]
                    struct PlayerJoinedSvc<T: MatchInternal>(pub Arc<T>);
                    impl<
                        T: MatchInternal,
                    > tonic::server::UnaryService<super::PlayerJoinedReq>
                    for PlayerJoinedSvc<T> {
                        type Response = super::PlayerJoinedRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlayerJoinedReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchInternal>::player_joined(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlayerJoinedSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchInternal/PlayerLeft" => {
                    #[allow(non_camel_case_types)]
                    struct PlayerLeftSvc<T: MatchInternal>(pub Arc<T>);
                    impl<
                        T: MatchInternal,
                    > tonic::server::UnaryService<super::PlayerLeftReq>
                    for PlayerLeftSvc<T> {
                        type Response = super::PlayerLeftRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlayerLeftReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchInternal>::player_left(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlayerLeftSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/myserver.matchservice.MatchInternal/MatchEnd" => {
                    #[allow(non_camel_case_types)]
                    struct MatchEndSvc<T: MatchInternal>(pub Arc<T>);
                    impl<
                        T: MatchInternal,
                    > tonic::server::UnaryService<super::MatchEndReq>
                    for MatchEndSvc<T> {
                        type Response = super::MatchEndRes;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MatchEndReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MatchInternal>::match_end(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MatchEndSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MatchInternalServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "myserver.matchservice.MatchInternal";
    impl<T> tonic::server::NamedService for MatchInternalServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
