// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerStatusReq {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusRes {
    #[prost(uint64, tag = "1")]
    pub connection_count: u64,
    #[prost(uint64, tag = "2")]
    pub room_count: u64,
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub max_body_len: u64,
    #[prost(uint64, tag = "5")]
    pub heartbeat_timeout_secs: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConfigReq {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConfigRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
