// This file is @generated by prost-build.
/// ============================================================
/// MatchStart
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStartReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    /// "1v1", "3v3", "5v5"
    #[prost(string, tag = "2")]
    pub mode: ::prost::alloc::string::String,
    /// 预留：段位（暂不使用）
    #[prost(int32, tag = "3")]
    pub rank_tier: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStartRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchCancel
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchCancelReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchCancelRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchStatus
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStatusReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchStatusRes {
    /// "idle", "matching", "matched", "in_room"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    /// matched/in_room 时有效
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
    /// 进入房间的临时凭证
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
    /// 预计等待时间
    #[prost(int64, tag = "5")]
    pub estimated_wait_secs: i64,
}
/// ============================================================
/// MatchEventStream
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEventStreamReq {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEvent {
    /// "matched", "match_failed", "match_cancelled"
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// CreateRoomAndJoin (GameServer -> MatchService)
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoomAndJoinReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub player_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoomAndJoinRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// PlayerJoined (GameServer -> MatchService)
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerJoinedReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerJoinedRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// PlayerLeft (GameServer -> MatchService)
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerLeftReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub player_id: ::prost::alloc::string::String,
    /// "normal", "disconnect", "kicked"
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerLeftRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// 所有人都离开，是否 abort 匹配
    #[prost(bool, tag = "2")]
    pub match_should_abort: bool,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
}
/// ============================================================
/// MatchEnd (GameServer -> MatchService)
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEndReq {
    #[prost(string, tag = "1")]
    pub match_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub room_id: ::prost::alloc::string::String,
    /// "game_over", "aborted", "timeout"
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchEndRes {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
}
