\set ON_ERROR_STOP on

SELECT format('CREATE DATABASE %I', dbname)
FROM (
  VALUES
    ('myserver_auth'),
    ('myserver_game'),
    ('myserver_chat'),
    ('myserver_announce'),
    ('myserver_mail')
) AS databases(dbname)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = databases.dbname
);
\gexec

\connect myserver_auth

CREATE TABLE IF NOT EXISTS player_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NOT NULL,
  guest_id varchar(128) NULL,
  login_name varchar(64) NULL,
  display_name varchar(64) NULL,
  account_type varchar(32) NOT NULL DEFAULT 'guest',
  status varchar(32) NOT NULL DEFAULT 'active',
  ban_expires_at timestamptz NULL,
  password_algo varchar(32) NULL,
  password_salt varchar(128) NULL,
  password_hash char(128) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_accounts_player_id UNIQUE (player_id),
  CONSTRAINT uk_player_accounts_guest_id UNIQUE (guest_id),
  CONSTRAINT uk_player_accounts_login_name UNIQUE (login_name)
);

CREATE INDEX IF NOT EXISTS idx_player_accounts_last_login_at
  ON player_accounts (last_login_at);

CREATE TABLE IF NOT EXISTS auth_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NULL,
  guest_id varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  access_token_hash char(64) NULL,
  ticket_hash char(64) NULL,
  client_ip varchar(64) NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_player_id
  ON auth_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_guest_id
  ON auth_audit_logs (guest_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_event_type
  ON auth_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_created_at
  ON auth_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS security_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  client_ip varchar(64) NULL,
  severity varchar(16) NOT NULL DEFAULT 'warning',
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN security_audit_logs.target_type IS 'ip, account, ticket, etc.';
COMMENT ON COLUMN security_audit_logs.target_value IS 'ip address, login_name, etc.';
COMMENT ON COLUMN security_audit_logs.severity IS 'info, warning, critical';

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type
  ON security_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target
  ON security_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_client_ip
  ON security_audit_logs (client_ip);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_severity
  ON security_audit_logs (severity);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at
  ON security_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(64) NOT NULL,
  display_name varchar(64) NULL,
  password_algo varchar(32) NOT NULL DEFAULT 'scrypt',
  password_salt varchar(128) NOT NULL,
  password_hash varchar(256) NOT NULL,
  role varchar(32) NOT NULL DEFAULT 'viewer',
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NULL,
  CONSTRAINT uk_admin_accounts_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_admin_accounts_role
  ON admin_accounts (role);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_status
  ON admin_accounts (status);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NULL,
  admin_username varchar(64) NULL,
  action varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  details_json jsonb NULL,
  ip varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id
  ON admin_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action
  ON admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
  ON admin_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
  ON admin_audit_logs (created_at);

\connect myserver_game

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS game_connection_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL CHECK (session_id >= 0),
  player_id varchar(64) NULL,
  peer_addr varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_player_id
  ON game_connection_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_event_type
  ON game_connection_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_created_at
  ON game_connection_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS room_event_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id varchar(64) NOT NULL,
  player_id varchar(64) NULL,
  owner_player_id varchar(64) NULL,
  event_type varchar(32) NOT NULL,
  room_state varchar(32) NULL,
  member_count integer NOT NULL DEFAULT 0 CHECK (member_count >= 0),
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_id
  ON room_event_logs (room_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_player_id
  ON room_event_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_event_type
  ON room_event_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_created_at
  ON room_event_logs (created_at);

CREATE TABLE IF NOT EXISTS metrics_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name varchar(64) NOT NULL,
  bucket_time integer NOT NULL CHECK (bucket_time >= 0),
  qps integer NOT NULL DEFAULT 0 CHECK (qps >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  online_value integer NOT NULL DEFAULT 0 CHECK (online_value >= 0),
  extra jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN metrics_archive.bucket_time IS '5-second bucket unix timestamp in seconds';
COMMENT ON COLUMN metrics_archive.online_value IS 'online_sessions / online_players / connections, etc.';
COMMENT ON COLUMN metrics_archive.extra IS 'service specific fields';

CREATE INDEX IF NOT EXISTS idx_metrics_archive_service_time
  ON metrics_archive (service_name, bucket_time);

CREATE TABLE IF NOT EXISTS player_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NOT NULL,
  level integer NOT NULL DEFAULT 1,
  hp bigint NOT NULL DEFAULT 0,
  inventory_data jsonb NOT NULL,
  warehouse_data jsonb NOT NULL,
  equipment_data jsonb NOT NULL,
  attr_base_data jsonb NOT NULL,
  visual_data jsonb NOT NULL,
  buffs_data jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_inventory_player_id UNIQUE (player_id)
);

CREATE INDEX IF NOT EXISTS idx_player_inventory_updated_at
  ON player_inventory (updated_at);

DROP TRIGGER IF EXISTS trg_player_inventory_updated_at ON player_inventory;
CREATE TRIGGER trg_player_inventory_updated_at
  BEFORE UPDATE ON player_inventory
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS player_inventory_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(128) NOT NULL,
  player_id varchar(64) NOT NULL,
  source varchar(64) NOT NULL,
  items_json jsonb NOT NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_inventory_grants_request_id UNIQUE (request_id)
);

CREATE INDEX IF NOT EXISTS idx_player_inventory_grants_player_id
  ON player_inventory_grants (player_id);

\connect myserver_chat

CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msg_id varchar(64) NOT NULL,
  chat_type smallint NOT NULL,
  sender_id varchar(64) NOT NULL,
  content text NOT NULL,
  created_at bigint NOT NULL,
  target_id varchar(64) NULL,
  group_id varchar(64) NULL,
  CONSTRAINT uk_chat_messages_msg_id UNIQUE (msg_id)
);

CREATE INDEX IF NOT EXISTS idx_sender
  ON chat_messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_target
  ON chat_messages (target_id);
CREATE INDEX IF NOT EXISTS idx_group
  ON chat_messages (group_id);
CREATE INDEX IF NOT EXISTS idx_created
  ON chat_messages (created_at);

CREATE TABLE IF NOT EXISTS chat_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  name varchar(128) NOT NULL,
  owner_id varchar(64) NOT NULL,
  created_at bigint NOT NULL,
  CONSTRAINT uk_chat_groups_group_id UNIQUE (group_id)
);

CREATE INDEX IF NOT EXISTS idx_owner
  ON chat_groups (owner_id);

CREATE TABLE IF NOT EXISTS chat_group_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  player_id varchar(64) NOT NULL,
  joined_at bigint NOT NULL,
  CONSTRAINT uk_group_player UNIQUE (group_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_player
  ON chat_group_members (player_id);

\connect myserver_announce

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announce_id varchar(64) NOT NULL,
  locale varchar(32) NOT NULL DEFAULT 'default',
  title varchar(256) NOT NULL,
  content text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  announce_type varchar(32) NOT NULL DEFAULT 'banner',
  target_group varchar(128) NOT NULL DEFAULT 'all',
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_announcements_announce_id UNIQUE (announce_id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_locale
  ON announcements (locale);
CREATE INDEX IF NOT EXISTS idx_announcements_priority
  ON announcements (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_time
  ON announcements (start_time, end_time);

DROP TRIGGER IF EXISTS trg_announcements_updated_at ON announcements;
CREATE TRIGGER trg_announcements_updated_at
  BEFORE UPDATE ON announcements
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

\connect myserver_mail

CREATE TABLE IF NOT EXISTS mails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  sender_type varchar(32) NOT NULL DEFAULT 'system',
  sender_id varchar(64) NOT NULL,
  sender_name varchar(128) NULL,
  from_player_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  title varchar(256) NOT NULL,
  content text NULL,
  attachments jsonb NULL,
  mail_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_id varchar(64) NULL,
  created_by_name varchar(128) NULL,
  status varchar(32) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  read_at timestamptz NULL,
  claimed_at timestamptz NULL,
  expires_at timestamptz NULL,
  CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
);

CREATE INDEX IF NOT EXISTS idx_mails_to_player_id
  ON mails (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mails_status
  ON mails (to_player_id, status);
CREATE INDEX IF NOT EXISTS idx_mails_created_at
  ON mails (created_at);

CREATE TABLE IF NOT EXISTS mail_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz NULL DEFAULT current_timestamp,
  locked_until timestamptz NULL,
  last_error varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  sent_at timestamptz NULL,
  CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
  CONSTRAINT fk_mail_notification_outbox_mail_id
    FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
  ON mail_notification_outbox (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
  ON mail_notification_outbox (to_player_id);
