\set ON_ERROR_STOP on

SELECT format('CREATE DATABASE %I', dbname)
FROM (
  VALUES
    ('myserver_auth'),
    ('myserver_game'),
    ('myserver_chat'),
    ('myserver_announce'),
    ('myserver_mail')
) AS databases(dbname)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = databases.dbname
);
\gexec

\connect myserver_auth

CREATE TABLE IF NOT EXISTS player_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NOT NULL,
  current_world_id bigint NOT NULL DEFAULT 0,
  guest_id varchar(128) NULL,
  login_name varchar(64) NULL,
  display_name varchar(64) NULL,
  account_type varchar(32) NOT NULL DEFAULT 'guest',
  status varchar(32) NOT NULL DEFAULT 'active',
  ban_expires_at timestamptz NULL,
  password_algo varchar(32) NULL,
  password_salt varchar(128) NULL,
  password_hash char(128) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_accounts_player_id UNIQUE (player_id),
  CONSTRAINT uk_player_accounts_guest_id UNIQUE (guest_id),
  CONSTRAINT uk_player_accounts_login_name UNIQUE (login_name)
);

CREATE INDEX IF NOT EXISTS idx_player_accounts_current_world_id
  ON player_accounts (current_world_id);
CREATE INDEX IF NOT EXISTS idx_player_accounts_last_login_at
  ON player_accounts (last_login_at);

CREATE TABLE IF NOT EXISTS auth_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id varchar(64) NULL,
  guest_id varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  access_token_hash char(64) NULL,
  ticket_hash char(64) NULL,
  client_ip varchar(64) NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_player_id
  ON auth_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_guest_id
  ON auth_audit_logs (guest_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_event_type
  ON auth_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_auth_audit_logs_created_at
  ON auth_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS security_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  client_ip varchar(64) NULL,
  severity varchar(16) NOT NULL DEFAULT 'warning',
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN security_audit_logs.target_type IS 'ip, account, ticket, etc.';
COMMENT ON COLUMN security_audit_logs.target_value IS 'ip address, login_name, etc.';
COMMENT ON COLUMN security_audit_logs.severity IS 'info, warning, critical';

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type
  ON security_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target
  ON security_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_client_ip
  ON security_audit_logs (client_ip);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_severity
  ON security_audit_logs (severity);
CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at
  ON security_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(64) NOT NULL,
  display_name varchar(64) NULL,
  password_algo varchar(32) NOT NULL DEFAULT 'scrypt',
  password_salt varchar(128) NOT NULL,
  password_hash varchar(256) NOT NULL,
  role varchar(32) NOT NULL DEFAULT 'viewer',
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NULL,
  CONSTRAINT uk_admin_accounts_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_admin_accounts_role
  ON admin_accounts (role);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_status
  ON admin_accounts (status);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NULL,
  admin_username varchar(64) NULL,
  action varchar(64) NOT NULL,
  target_type varchar(32) NULL,
  target_value varchar(256) NULL,
  details_json jsonb NULL,
  ip varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id
  ON admin_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action
  ON admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
  ON admin_audit_logs (target_type, target_value);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
  ON admin_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS myforge_agents (
  agent_id varchar(128) PRIMARY KEY,
  project_id varchar(128) NOT NULL,
  label varchar(128) NULL,
  public_key_fingerprint varchar(64) NOT NULL,
  configured boolean NOT NULL DEFAULT true,
  status varchar(32) NOT NULL DEFAULT 'offline',
  hostname varchar(255) NULL,
  platform varchar(32) NULL,
  agent_version varchar(64) NULL,
  forge_root_summary_json jsonb NULL,
  capabilities_json jsonb NULL,
  limits_json jsonb NULL,
  effective_limits_json jsonb NULL,
  connection_id uuid NULL,
  last_registered_at timestamptz NULL,
  connected_at timestamptz NULL,
  last_seen_at timestamptz NULL,
  disconnected_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_myforge_agents_agent_id CHECK (agent_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  CONSTRAINT ck_myforge_agents_project_id CHECK (project_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  CONSTRAINT ck_myforge_agents_fingerprint CHECK (public_key_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_agents_status CHECK (status IN ('online', 'offline')),
  CONSTRAINT ck_myforge_agents_connection_status CHECK ((status = 'online') = (connection_id IS NOT NULL)),
  CONSTRAINT ck_myforge_agents_root_summary CHECK (forge_root_summary_json IS NULL OR jsonb_typeof(forge_root_summary_json) = 'object'),
  CONSTRAINT ck_myforge_agents_capabilities CHECK (capabilities_json IS NULL OR jsonb_typeof(capabilities_json) = 'object'),
  CONSTRAINT ck_myforge_agents_limits CHECK (limits_json IS NULL OR jsonb_typeof(limits_json) = 'object'),
  CONSTRAINT ck_myforge_agents_effective_limits CHECK (effective_limits_json IS NULL OR jsonb_typeof(effective_limits_json) = 'object')
);

ALTER TABLE myforge_agents
  ADD COLUMN IF NOT EXISTS connection_id uuid NULL;

CREATE INDEX IF NOT EXISTS idx_myforge_agents_configured_status
  ON myforge_agents (configured, status, agent_id);
CREATE INDEX IF NOT EXISTS idx_myforge_agents_project_id
  ON myforge_agents (project_id, agent_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_myforge_agents_connection_id
  ON myforge_agents (connection_id)
  WHERE connection_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS myforge_task_runs (
  request_id uuid PRIMARY KEY,
  task_type varchar(64) NOT NULL,
  project_id varchar(128) NOT NULL,
  agent_id varchar(128) NOT NULL,
  status varchar(32) NOT NULL,
  queue_reason varchar(32) NULL,
  execution_mode varchar(32) NULL,
  connection_id uuid NULL,
  artifact_file varchar(512) NOT NULL,
  consumer_target_file varchar(512) NULL,
  rules_file varchar(512) NOT NULL,
  prompt_json jsonb NOT NULL,
  rendered_prompt text NOT NULL,
  command_preview text NOT NULL,
  command_digest varchar(64) NULL,
  command_expires_at timestamptz NULL,
  timeout_ms integer NOT NULL,
  max_output_bytes integer NOT NULL,
  stdout_preview text NULL,
  stderr_preview text NULL,
  stdout_bytes bigint NULL,
  stderr_bytes bigint NULL,
  stdout_truncated boolean NOT NULL DEFAULT false,
  stderr_truncated boolean NOT NULL DEFAULT false,
  exit_code integer NULL,
  artifact_json jsonb NULL,
  audit_json jsonb NULL,
  result_digest varchar(64) NULL,
  error_code varchar(64) NULL,
  error_message text NULL,
  created_by_admin_id bigint NULL,
  created_by_admin_username varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  queue_expires_at timestamptz NOT NULL,
  dispatched_at timestamptz NULL,
  started_at timestamptz NULL,
  cancel_requested_at timestamptz NULL,
  cancel_deadline_at timestamptz NULL,
  completed_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_myforge_tasks_type CHECK (task_type = 'fangyuan.blueprint.generate'),
  CONSTRAINT ck_myforge_tasks_status CHECK (status IN ('queued', 'dispatched', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled')),
  CONSTRAINT ck_myforge_tasks_queue_reason CHECK (queue_reason IS NULL OR queue_reason IN ('agent_offline', 'agent_busy')),
  CONSTRAINT ck_myforge_tasks_queue_reason_status CHECK (queue_reason IS NULL OR status = 'queued'),
  CONSTRAINT ck_myforge_tasks_execution_mode CHECK (execution_mode IS NULL OR execution_mode IN ('codex_exec', 'dry_run')),
  CONSTRAINT ck_myforge_tasks_prompt_json CHECK (jsonb_typeof(prompt_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_artifact_json CHECK (artifact_json IS NULL OR jsonb_typeof(artifact_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_audit_json CHECK (audit_json IS NULL OR jsonb_typeof(audit_json) = 'object'),
  CONSTRAINT ck_myforge_tasks_error_code CHECK (error_code IS NULL OR error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT ck_myforge_tasks_timeout CHECK (timeout_ms BETWEEN 1000 AND 1800000),
  CONSTRAINT ck_myforge_tasks_max_output CHECK (max_output_bytes BETWEEN 4096 AND 4194304),
  CONSTRAINT ck_myforge_tasks_stdout_bytes CHECK (stdout_bytes IS NULL OR stdout_bytes >= 0),
  CONSTRAINT ck_myforge_tasks_stderr_bytes CHECK (stderr_bytes IS NULL OR stderr_bytes >= 0),
  CONSTRAINT ck_myforge_tasks_command_digest CHECK (command_digest IS NULL OR command_digest ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_tasks_result_digest CHECK (result_digest IS NULL OR result_digest ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_myforge_tasks_cancel_pair CHECK ((cancel_requested_at IS NULL) = (cancel_deadline_at IS NULL)),
  CONSTRAINT ck_myforge_tasks_cancel_order CHECK (cancel_deadline_at IS NULL OR cancel_deadline_at >= cancel_requested_at),
  CONSTRAINT ck_myforge_tasks_queue_expiry CHECK (queue_expires_at >= created_at),
  CONSTRAINT ck_myforge_tasks_completion CHECK ((status IN ('completed', 'completed_with_errors', 'failed', 'cancelled')) = (completed_at IS NOT NULL)),
  CONSTRAINT ck_myforge_tasks_dispatch_fields CHECK (
    (connection_id IS NULL AND execution_mode IS NULL AND command_digest IS NULL AND command_expires_at IS NULL AND dispatched_at IS NULL)
    OR
    (connection_id IS NOT NULL AND execution_mode IS NOT NULL AND command_digest IS NOT NULL AND command_expires_at IS NOT NULL AND dispatched_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_myforge_tasks_agent_status_created
  ON myforge_task_runs (agent_id, status, created_at, request_id);
CREATE INDEX IF NOT EXISTS idx_myforge_tasks_project_created
  ON myforge_task_runs (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_myforge_tasks_created_at
  ON myforge_task_runs (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_myforge_tasks_agent_active
  ON myforge_task_runs (agent_id)
  WHERE status IN ('dispatched', 'running');

CREATE TABLE IF NOT EXISTS id_origins (
  origin_id smallint PRIMARY KEY CHECK (origin_id >= 0 AND origin_id <= 1023),
  origin_key varchar(64) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS worlds (
  world_id bigint PRIMARY KEY CHECK (world_id >= 0),
  world_key varchar(64) NOT NULL UNIQUE,
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  retired_at timestamptz NULL,
  metadata_json jsonb NULL
);

CREATE TABLE IF NOT EXISTS world_origin_memberships (
  world_id bigint NOT NULL REFERENCES worlds(world_id),
  origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  joined_at timestamptz NOT NULL DEFAULT current_timestamp,
  left_at timestamptz NULL,
  PRIMARY KEY (world_id, origin_id, joined_at)
);

CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_origin_id
  ON world_origin_memberships (origin_id);
CREATE INDEX IF NOT EXISTS idx_world_origin_memberships_joined_at
  ON world_origin_memberships (joined_at);

CREATE TABLE IF NOT EXISTS world_merge_events (
  merge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_world_id bigint NOT NULL REFERENCES worlds(world_id),
  active_origin_id smallint NOT NULL REFERENCES id_origins(origin_id),
  source_world_ids bigint[] NOT NULL,
  source_origin_ids smallint[] NOT NULL,
  merged_at timestamptz NOT NULL DEFAULT current_timestamp,
  operator varchar(64) NULL,
  details_json jsonb NULL
);

CREATE INDEX IF NOT EXISTS idx_world_merge_events_target_world_id
  ON world_merge_events (target_world_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_active_origin_id
  ON world_merge_events (active_origin_id);
CREATE INDEX IF NOT EXISTS idx_world_merge_events_merged_at
  ON world_merge_events (merged_at);

INSERT INTO id_origins (origin_id, origin_key, metadata_json)
VALUES (0, 'local-dev', '{"type":"local"}'::jsonb)
ON CONFLICT (origin_id) DO NOTHING;

INSERT INTO worlds (world_id, world_key, active_origin_id, metadata_json)
VALUES (0, 'local-dev', 0, '{"type":"local"}'::jsonb)
ON CONFLICT (world_id) DO NOTHING;

INSERT INTO world_origin_memberships (world_id, origin_id, joined_at)
SELECT 0, 0, current_timestamp
WHERE NOT EXISTS (
  SELECT 1 FROM world_origin_memberships WHERE world_id = 0 AND origin_id = 0
);

\connect myserver_game

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS game_connection_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL CHECK (session_id >= 0),
  player_id varchar(64) NULL,
  account_player_id varchar(64) NULL,
  character_id varchar(64) NULL,
  peer_addr varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_player_id
  ON game_connection_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_account_player_id
  ON game_connection_audit_logs (account_player_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_character_id
  ON game_connection_audit_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_event_type
  ON game_connection_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_created_at
  ON game_connection_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS room_event_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id varchar(64) NOT NULL,
  room_subject_id varchar(64) NULL,
  player_id varchar(64) NULL,
  account_player_id varchar(64) NULL,
  character_id varchar(64) NULL,
  owner_player_id varchar(64) NULL,
  owner_character_id varchar(64) NULL,
  event_type varchar(32) NOT NULL,
  room_state varchar(32) NULL,
  member_count integer NOT NULL DEFAULT 0 CHECK (member_count >= 0),
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_id
  ON room_event_logs (room_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_subject_id
  ON room_event_logs (room_subject_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_player_id
  ON room_event_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_account_player_id
  ON room_event_logs (account_player_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_character_id
  ON room_event_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_owner_character_id
  ON room_event_logs (owner_character_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_event_type
  ON room_event_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_created_at
  ON room_event_logs (created_at);

CREATE TABLE IF NOT EXISTS metrics_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name varchar(64) NOT NULL,
  bucket_time integer NOT NULL CHECK (bucket_time >= 0),
  qps integer NOT NULL DEFAULT 0 CHECK (qps >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  online_value integer NOT NULL DEFAULT 0 CHECK (online_value >= 0),
  extra jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN metrics_archive.bucket_time IS '5-second bucket unix timestamp in seconds';
COMMENT ON COLUMN metrics_archive.online_value IS 'online_sessions / online_players / connections, etc.';
COMMENT ON COLUMN metrics_archive.extra IS 'service specific fields';

CREATE INDEX IF NOT EXISTS idx_metrics_archive_service_time
  ON metrics_archive (service_name, bucket_time);

CREATE TABLE IF NOT EXISTS characters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  account_player_id varchar(64) NOT NULL,
  world_id bigint NOT NULL DEFAULT 0,
  name varchar(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'active',
  appearance_json jsonb NOT NULL,
  scene_id integer NOT NULL,
  x real NOT NULL DEFAULT 0,
  y real NOT NULL DEFAULT 0,
  dir_x real NOT NULL DEFAULT 0,
  dir_y real NOT NULL DEFAULT 1,
  affinity_earth integer NOT NULL DEFAULT 2500,
  affinity_fire integer NOT NULL DEFAULT 2500,
  affinity_water integer NOT NULL DEFAULT 2500,
  affinity_wind integer NOT NULL DEFAULT 2500,
  mastery_earth integer NOT NULL DEFAULT 0,
  mastery_fire integer NOT NULL DEFAULT 0,
  mastery_water integer NOT NULL DEFAULT 0,
  mastery_wind integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NULL,
  deleted_at timestamptz NULL,
  CONSTRAINT uk_characters_character_id UNIQUE (character_id),
  CONSTRAINT ck_characters_affinity_non_negative CHECK (
    affinity_earth >= 0
    AND affinity_fire >= 0
    AND affinity_water >= 0
    AND affinity_wind >= 0
  ),
  CONSTRAINT ck_characters_affinity_total CHECK (
    affinity_earth + affinity_fire + affinity_water + affinity_wind = 10000
  ),
  CONSTRAINT ck_characters_mastery_non_negative CHECK (
    mastery_earth >= 0
    AND mastery_fire >= 0
    AND mastery_water >= 0
    AND mastery_wind >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_characters_account_player_id
  ON characters (account_player_id);
CREATE INDEX IF NOT EXISTS idx_characters_world_id
  ON characters (world_id);
CREATE INDEX IF NOT EXISTS idx_characters_status
  ON characters (status);
CREATE INDEX IF NOT EXISTS idx_characters_created_at
  ON characters (created_at);

CREATE TABLE IF NOT EXISTS character_element_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  source_type varchar(32) NOT NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  affinity_earth_delta integer NOT NULL DEFAULT 0,
  affinity_fire_delta integer NOT NULL DEFAULT 0,
  affinity_water_delta integer NOT NULL DEFAULT 0,
  affinity_wind_delta integer NOT NULL DEFAULT 0,
  mastery_earth_delta integer NOT NULL DEFAULT 0,
  mastery_fire_delta integer NOT NULL DEFAULT 0,
  mastery_water_delta integer NOT NULL DEFAULT 0,
  mastery_wind_delta integer NOT NULL DEFAULT 0,
  before_json jsonb NOT NULL,
  after_json jsonb NOT NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_element_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_element_logs_character_id
  ON character_element_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_created_at_desc
  ON character_element_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_character_created_at_desc
  ON character_element_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_source
  ON character_element_logs (source_type, source_id);

CREATE TABLE IF NOT EXISTS character_disciplines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  discipline_id varchar(64) NOT NULL,
  points bigint NOT NULL DEFAULT 0 CHECK (points >= 0),
  tier varchar(32) NOT NULL DEFAULT 'novice',
  active boolean NOT NULL DEFAULT false,
  learned_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_disciplines_discipline UNIQUE (character_id, discipline_id),
  CONSTRAINT fk_character_disciplines_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_disciplines_character_id
  ON character_disciplines (character_id);
CREATE INDEX IF NOT EXISTS idx_character_disciplines_character_active
  ON character_disciplines (character_id, active);
CREATE INDEX IF NOT EXISTS idx_character_disciplines_updated_at
  ON character_disciplines (updated_at);

DROP TRIGGER IF EXISTS trg_character_disciplines_updated_at ON character_disciplines;
CREATE TRIGGER trg_character_disciplines_updated_at
  BEFORE UPDATE ON character_disciplines
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_discipline_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  discipline_id varchar(64) NOT NULL,
  action varchar(32) NOT NULL,
  source_type varchar(32) NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  before_json jsonb NULL,
  after_json jsonb NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_discipline_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_character_id
  ON character_discipline_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_created_at_desc
  ON character_discipline_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_character_created_at_desc
  ON character_discipline_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_discipline_id
  ON character_discipline_logs (discipline_id);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_source
  ON character_discipline_logs (source_type, source_id);

CREATE TABLE IF NOT EXISTS character_titles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  title_id varchar(64) NOT NULL,
  source_type varchar(32) NOT NULL,
  source_id varchar(128) NULL,
  is_equipped boolean NOT NULL DEFAULT false,
  unlocked_at timestamptz NOT NULL DEFAULT current_timestamp,
  expires_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_titles_title UNIQUE (character_id, title_id),
  CONSTRAINT fk_character_titles_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

COMMENT ON TABLE character_titles IS
  'A character owns many titles. Equip only one main display title by service transaction: unequip old title, then equip the new title; avoid partial unique indexes for cross-database compatibility.';

CREATE INDEX IF NOT EXISTS idx_character_titles_character_id
  ON character_titles (character_id);
CREATE INDEX IF NOT EXISTS idx_character_titles_character_equipped
  ON character_titles (character_id, is_equipped);
CREATE INDEX IF NOT EXISTS idx_character_titles_is_equipped
  ON character_titles (is_equipped);
CREATE INDEX IF NOT EXISTS idx_character_titles_expires_at
  ON character_titles (expires_at);

DROP TRIGGER IF EXISTS trg_character_titles_updated_at ON character_titles;
CREATE TRIGGER trg_character_titles_updated_at
  BEFORE UPDATE ON character_titles
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_title_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  title_id varchar(64) NOT NULL,
  action varchar(32) NOT NULL,
  source_type varchar(32) NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  before_json jsonb NULL,
  after_json jsonb NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_title_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_title_logs_character_id
  ON character_title_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_created_at_desc
  ON character_title_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_character_created_at_desc
  ON character_title_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_title_id
  ON character_title_logs (title_id);

CREATE TABLE IF NOT EXISTS character_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  hp bigint NOT NULL DEFAULT 0,
  inventory_data jsonb NOT NULL,
  warehouse_data jsonb NOT NULL,
  equipment_data jsonb NOT NULL,
  attr_base_data jsonb NOT NULL,
  visual_data jsonb NOT NULL,
  buffs_data jsonb NOT NULL,
  progress_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_inventory_character_id UNIQUE (character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_inventory_updated_at
  ON character_inventory (updated_at);

DROP TRIGGER IF EXISTS trg_character_inventory_updated_at ON character_inventory;
CREATE TRIGGER trg_character_inventory_updated_at
  BEFORE UPDATE ON character_inventory
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_inventory_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  source varchar(64) NOT NULL,
  items_json jsonb NOT NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_inventory_grants_request_id UNIQUE (request_id)
);

CREATE INDEX IF NOT EXISTS idx_character_inventory_grants_character_id
  ON character_inventory_grants (character_id);

\connect myserver_chat

CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msg_id varchar(64) NOT NULL,
  chat_type smallint NOT NULL,
  sender_id varchar(64) NOT NULL,
  content text NOT NULL,
  created_at bigint NOT NULL,
  target_id varchar(64) NULL,
  group_id varchar(64) NULL,
  CONSTRAINT uk_chat_messages_msg_id UNIQUE (msg_id)
);

CREATE INDEX IF NOT EXISTS idx_sender
  ON chat_messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_target
  ON chat_messages (target_id);
CREATE INDEX IF NOT EXISTS idx_group
  ON chat_messages (group_id);
CREATE INDEX IF NOT EXISTS idx_created
  ON chat_messages (created_at);

CREATE TABLE IF NOT EXISTS chat_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  name varchar(128) NOT NULL,
  owner_id varchar(64) NOT NULL,
  created_at bigint NOT NULL,
  CONSTRAINT uk_chat_groups_group_id UNIQUE (group_id)
);

CREATE INDEX IF NOT EXISTS idx_owner
  ON chat_groups (owner_id);

CREATE TABLE IF NOT EXISTS chat_group_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(64) NOT NULL,
  player_id varchar(64) NOT NULL,
  joined_at bigint NOT NULL,
  CONSTRAINT uk_group_player UNIQUE (group_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_player
  ON chat_group_members (player_id);

\connect myserver_announce

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announce_id varchar(64) NOT NULL,
  world_id bigint NOT NULL DEFAULT 0,
  locale varchar(32) NOT NULL DEFAULT 'default',
  title varchar(256) NOT NULL,
  content text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  announce_type varchar(32) NOT NULL DEFAULT 'banner',
  target_group varchar(128) NOT NULL DEFAULT 'all',
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_announcements_announce_id UNIQUE (announce_id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_locale
  ON announcements (locale);
CREATE INDEX IF NOT EXISTS idx_announcements_world_id
  ON announcements (world_id);
CREATE INDEX IF NOT EXISTS idx_announcements_priority
  ON announcements (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_time
  ON announcements (start_time, end_time);

DROP TRIGGER IF EXISTS trg_announcements_updated_at ON announcements;
CREATE TRIGGER trg_announcements_updated_at
  BEFORE UPDATE ON announcements
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

\connect myserver_mail

CREATE TABLE IF NOT EXISTS mails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  world_id bigint NOT NULL DEFAULT 0,
  sender_type varchar(32) NOT NULL DEFAULT 'system',
  sender_id varchar(64) NOT NULL,
  sender_name varchar(128) NULL,
  from_player_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  title varchar(256) NOT NULL,
  content text NULL,
  attachments jsonb NULL,
  mail_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_id varchar(64) NULL,
  created_by_name varchar(128) NULL,
  status varchar(32) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  read_at timestamptz NULL,
  claimed_at timestamptz NULL,
  expires_at timestamptz NULL,
  CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
);

CREATE INDEX IF NOT EXISTS idx_mails_to_player_id
  ON mails (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mails_world_id
  ON mails (world_id);
CREATE INDEX IF NOT EXISTS idx_mails_status
  ON mails (to_player_id, status);
CREATE INDEX IF NOT EXISTS idx_mails_created_at
  ON mails (created_at);

CREATE TABLE IF NOT EXISTS mail_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz NULL DEFAULT current_timestamp,
  locked_until timestamptz NULL,
  last_error varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  sent_at timestamptz NULL,
  CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
  CONSTRAINT fk_mail_notification_outbox_mail_id
    FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
  ON mail_notification_outbox (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
  ON mail_notification_outbox (to_player_id);
