-- Logical owner: game-server
-- Compatibility phase: expand
-- Irreversible risk: none
-- Transaction: required
-- Lock timeout: 5s
-- Statement timeout: 60s
-- Backup point: not-required
-- Recovery command: SQLx rolls back the transaction; correct the migration and rerun db up.

-- Activity configuration is independent from CharacterProgressTable.csv and task progress.
-- Published versions and their configuration children are immutable snapshots.
CREATE TABLE IF NOT EXISTS activity (
  activity_id varchar(64) PRIMARY KEY,
  activity_key varchar(128) NOT NULL UNIQUE,
  activity_type varchar(64) NOT NULL,
  scope varchar(16) NOT NULL DEFAULT 'character',
  status varchar(16) NOT NULL DEFAULT 'draft',
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  claim_deadline timestamptz NOT NULL,
  timezone varchar(64) NOT NULL,
  show_before_start boolean NOT NULL DEFAULT false,
  claim_mode varchar(32) NOT NULL DEFAULT 'manual',
  current_version integer NULL,
  created_by varchar(128) NOT NULL,
  published_at timestamptz NULL,
  offlined_at timestamptz NULL,
  offline_reason varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT ck_activity_scope CHECK (scope IN ('character', 'account')),
  CONSTRAINT ck_activity_status CHECK (status IN ('draft', 'published', 'running', 'ended', 'offline', 'archived')),
  CONSTRAINT ck_activity_type CHECK (btrim(activity_type) <> ''),
  CONSTRAINT ck_activity_timezone CHECK (btrim(timezone) <> ''),
  CONSTRAINT ck_activity_window CHECK (start_at < end_at),
  CONSTRAINT ck_activity_claim_deadline CHECK (claim_deadline >= end_at),
  CONSTRAINT ck_activity_claim_mode CHECK (claim_mode IN ('manual', 'automatic'))
);

CREATE INDEX IF NOT EXISTS idx_activity_status_window
  ON activity (status, start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_activity_type_status
  ON activity (activity_type, status);

CREATE TABLE IF NOT EXISTS activity_version (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  public_config_json jsonb NOT NULL,
  type_config_json jsonb NOT NULL,
  config_digest varchar(71) NOT NULL,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  claim_deadline timestamptz NOT NULL,
  timezone varchar(64) NOT NULL,
  published_at timestamptz NULL,
  published_by varchar(128) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_activity_version_activity_version UNIQUE (activity_id, version_no),
  CONSTRAINT fk_activity_version_activity FOREIGN KEY (activity_id) REFERENCES activity(activity_id),
  CONSTRAINT ck_activity_version_no CHECK (version_no > 0),
  CONSTRAINT ck_activity_version_public_config CHECK (jsonb_typeof(public_config_json) = 'object'),
  CONSTRAINT ck_activity_version_type_config CHECK (jsonb_typeof(type_config_json) = 'object'),
  CONSTRAINT ck_activity_version_digest CHECK (config_digest ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT ck_activity_version_timezone CHECK (btrim(timezone) <> ''),
  CONSTRAINT ck_activity_version_window CHECK (start_at < end_at),
  CONSTRAINT ck_activity_version_claim_deadline CHECK (claim_deadline >= end_at),
  CONSTRAINT ck_activity_version_published_pair CHECK ((published_at IS NULL AND published_by IS NULL) OR (published_at IS NOT NULL AND published_by IS NOT NULL AND btrim(published_by) <> ''))
);

CREATE INDEX IF NOT EXISTS idx_activity_version_activity_created
  ON activity_version (activity_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_activity_version_digest
  ON activity_version (activity_id, config_digest);

CREATE TABLE IF NOT EXISTS activity_reward_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  reward_group_key varchar(64) NOT NULL,
  selection_mode varchar(32) NOT NULL DEFAULT 'fixed',
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_activity_reward_group_key UNIQUE (activity_id, version_no, reward_group_key),
  CONSTRAINT fk_activity_reward_group_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_activity_reward_group_key CHECK (reward_group_key ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
  CONSTRAINT ck_activity_reward_group_selection CHECK (selection_mode IN ('fixed', 'weighted')),
  CONSTRAINT ck_activity_reward_group_config CHECK (jsonb_typeof(config_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_activity_reward_group_version
  ON activity_reward_group (activity_id, version_no);

CREATE TABLE IF NOT EXISTS activity_reward_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  reward_group_key varchar(64) NOT NULL,
  reward_type varchar(32) NOT NULL,
  asset_key varchar(128) NOT NULL,
  quantity bigint NOT NULL,
  weight bigint NULL,
  reward_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_activity_reward_item_group FOREIGN KEY (activity_id, version_no, reward_group_key) REFERENCES activity_reward_group(activity_id, version_no, reward_group_key),
  CONSTRAINT ck_activity_reward_item_type CHECK (reward_type IN ('item', 'currency', 'title', 'custom')),
  CONSTRAINT ck_activity_reward_item_asset_key CHECK (btrim(asset_key) <> ''),
  CONSTRAINT ck_activity_reward_item_quantity CHECK (quantity > 0),
  CONSTRAINT ck_activity_reward_item_weight CHECK (weight IS NULL OR weight > 0),
  CONSTRAINT ck_activity_reward_item_json CHECK (jsonb_typeof(reward_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_activity_reward_item_group
  ON activity_reward_item (activity_id, version_no, reward_group_key);

CREATE TABLE IF NOT EXISTS activity_stage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  stage_id varchar(64) NOT NULL,
  stage_no integer NOT NULL,
  qualification_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  period_strategy varchar(32) NOT NULL DEFAULT 'once',
  reward_group_key varchar(64) NOT NULL,
  max_claims integer NOT NULL DEFAULT 1,
  reset_policy varchar(32) NOT NULL DEFAULT 'none',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_activity_stage_id UNIQUE (activity_id, version_no, stage_id),
  CONSTRAINT uk_activity_stage_no UNIQUE (activity_id, version_no, stage_no),
  CONSTRAINT fk_activity_stage_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT fk_activity_stage_reward_group FOREIGN KEY (activity_id, version_no, reward_group_key) REFERENCES activity_reward_group(activity_id, version_no, reward_group_key),
  CONSTRAINT ck_activity_stage_id CHECK (stage_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
  CONSTRAINT ck_activity_stage_no CHECK (stage_no > 0),
  CONSTRAINT ck_activity_stage_qualification CHECK (jsonb_typeof(qualification_json) = 'object'),
  CONSTRAINT ck_activity_stage_period CHECK (period_strategy IN ('once', 'natural_day', 'natural_week', 'activity_stage')),
  CONSTRAINT ck_activity_stage_max_claims CHECK (max_claims > 0),
  CONSTRAINT ck_activity_stage_reset CHECK (reset_policy IN ('none', 'reset', 'carry'))
);

CREATE INDEX IF NOT EXISTS idx_activity_stage_version
  ON activity_stage (activity_id, version_no, stage_no);

CREATE TABLE IF NOT EXISTS player_activity_state (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  current_stage_id varchar(64) NULL,
  progress_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  type_state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  state_revision bigint NOT NULL DEFAULT 0,
  last_event_key varchar(128) NULL,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_player_activity_state_owner_version UNIQUE (character_id, activity_id, version_no),
  CONSTRAINT fk_player_activity_state_character FOREIGN KEY (character_id) REFERENCES characters(character_id),
  CONSTRAINT fk_player_activity_state_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_player_activity_state_progress CHECK (jsonb_typeof(progress_json) = 'object'),
  CONSTRAINT ck_player_activity_state_type_state CHECK (jsonb_typeof(type_state_json) = 'object'),
  CONSTRAINT ck_player_activity_state_revision CHECK (state_revision >= 0)
);

CREATE INDEX IF NOT EXISTS idx_player_activity_state_activity
  ON player_activity_state (activity_id, version_no, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_player_activity_state_character
  ON player_activity_state (character_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS activity_claim_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  activity_type varchar(64) NOT NULL,
  action_type varchar(16) NOT NULL,
  stage_id varchar(64) NULL,
  period_key varchar(128) NOT NULL,
  semantic_claim_key varchar(256) NOT NULL,
  client_request_id varchar(128) NULL,
  status varchar(32) NOT NULL DEFAULT 'processing',
  reward_snapshot_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  cost_snapshot_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  rule_digest varchar(71) NULL,
  error_code varchar(64) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  completed_at timestamptz NULL,
  last_retry_at timestamptz NULL,
  CONSTRAINT uk_activity_claim_semantic UNIQUE (character_id, activity_id, version_no, semantic_claim_key),
  CONSTRAINT fk_activity_claim_character FOREIGN KEY (character_id) REFERENCES characters(character_id),
  CONSTRAINT fk_activity_claim_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_activity_claim_action CHECK (action_type IN ('claim', 'draw')),
  CONSTRAINT ck_activity_claim_status CHECK (status IN ('processing', 'granted', 'retryable_failure', 'permanent_failure', 'manual_review')),
  CONSTRAINT ck_activity_claim_period_key CHECK (btrim(period_key) <> ''),
  CONSTRAINT ck_activity_claim_semantic_key CHECK (btrim(semantic_claim_key) <> ''),
  CONSTRAINT ck_activity_claim_reward_json CHECK (jsonb_typeof(reward_snapshot_json) = 'array'),
  CONSTRAINT ck_activity_claim_cost_json CHECK (jsonb_typeof(cost_snapshot_json) = 'array'),
  CONSTRAINT ck_activity_claim_rule_digest CHECK (rule_digest IS NULL OR rule_digest ~ '^sha256:[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_activity_claim_client_request
  ON activity_claim_record (character_id, client_request_id)
  WHERE client_request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_activity_claim_owner_activity
  ON activity_claim_record (character_id, activity_id, version_no, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_claim_stage_period
  ON activity_claim_record (activity_id, version_no, stage_id, period_key);

CREATE TABLE IF NOT EXISTS activity_draw_result (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id bigint NOT NULL UNIQUE REFERENCES activity_claim_record(id),
  character_id varchar(64) NOT NULL,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  reward_group_key varchar(64) NOT NULL,
  pool_digest varchar(71) NOT NULL,
  random_algorithm_version varchar(32) NOT NULL,
  selected_item_id bigint NULL,
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_activity_draw_result_character FOREIGN KEY (character_id) REFERENCES characters(character_id),
  CONSTRAINT fk_activity_draw_result_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_activity_draw_result_pool_digest CHECK (pool_digest ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT ck_activity_draw_result_json CHECK (jsonb_typeof(result_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_activity_draw_result_owner
  ON activity_draw_result (character_id, activity_id, version_no, created_at DESC);

CREATE TABLE IF NOT EXISTS reward_grant_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id bigint NULL REFERENCES activity_claim_record(id),
  character_id varchar(64) NOT NULL,
  activity_id varchar(64) NOT NULL,
  version_no integer NOT NULL,
  request_id varchar(128) NOT NULL UNIQUE,
  delivery_id varchar(128) NULL,
  asset_ledger_id bigint NULL,
  mail_id varchar(64) NULL,
  delivery_method varchar(32) NOT NULL,
  status varchar(32) NOT NULL,
  reward_snapshot_json jsonb NOT NULL,
  result_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_reward_grant_ledger_character FOREIGN KEY (character_id) REFERENCES characters(character_id),
  CONSTRAINT fk_reward_grant_ledger_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_reward_grant_ledger_method CHECK (delivery_method IN ('direct', 'mail', 'inventory_required')),
  CONSTRAINT ck_reward_grant_ledger_status CHECK (status IN ('pending', 'granted', 'retryable_failure', 'permanent_failure', 'manual_review')),
  CONSTRAINT ck_reward_grant_ledger_reward_json CHECK (jsonb_typeof(reward_snapshot_json) = 'array'),
  CONSTRAINT ck_reward_grant_ledger_result_json CHECK (jsonb_typeof(result_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_reward_grant_ledger_owner
  ON reward_grant_ledger (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reward_grant_ledger_activity
  ON reward_grant_ledger (activity_id, version_no, created_at DESC);

CREATE TABLE IF NOT EXISTS activity_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id varchar(64) NULL,
  version_no integer NULL,
  event_type varchar(64) NOT NULL,
  actor_type varchar(32) NOT NULL,
  actor_id varchar(128) NOT NULL,
  reason varchar(512) NOT NULL,
  details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_activity_audit_activity FOREIGN KEY (activity_id) REFERENCES activity(activity_id),
  CONSTRAINT fk_activity_audit_version FOREIGN KEY (activity_id, version_no) REFERENCES activity_version(activity_id, version_no),
  CONSTRAINT ck_activity_audit_event_type CHECK (event_type IN ('draft_created', 'draft_updated', 'published', 'offlined', 'archived', 'config_changed', 'reward_changed')),
  CONSTRAINT ck_activity_audit_actor_type CHECK (actor_type IN ('admin', 'system')),
  CONSTRAINT ck_activity_audit_actor CHECK (btrim(actor_id) <> ''),
  CONSTRAINT ck_activity_audit_reason CHECK (btrim(reason) <> ''),
  CONSTRAINT ck_activity_audit_details CHECK (jsonb_typeof(details_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_activity_audit_activity
  ON activity_audit_log (activity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_audit_actor
  ON activity_audit_log (actor_id, created_at DESC);

CREATE OR REPLACE FUNCTION reject_published_activity_config_mutation()
RETURNS trigger AS $$
DECLARE
  target_activity_id varchar(64);
  target_version_no integer;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    IF EXISTS (
      SELECT 1
      FROM activity_version
      WHERE activity_id = OLD.activity_id
        AND version_no = OLD.version_no
        AND published_at IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'published activity configuration is immutable';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN
    target_activity_id := OLD.activity_id;
    target_version_no := OLD.version_no;
  ELSE
    target_activity_id := NEW.activity_id;
    target_version_no := NEW.version_no;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    IF EXISTS (
      SELECT 1
      FROM activity_version
      WHERE activity_id = target_activity_id
        AND version_no = target_version_no
        AND published_at IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'published activity configuration is immutable';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_reward_group_immutable ON activity_reward_group;
CREATE TRIGGER trg_activity_reward_group_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON activity_reward_group
  FOR EACH ROW EXECUTE FUNCTION reject_published_activity_config_mutation();
DROP TRIGGER IF EXISTS trg_activity_reward_item_immutable ON activity_reward_item;
CREATE TRIGGER trg_activity_reward_item_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON activity_reward_item
  FOR EACH ROW EXECUTE FUNCTION reject_published_activity_config_mutation();
DROP TRIGGER IF EXISTS trg_activity_stage_immutable ON activity_stage;
CREATE TRIGGER trg_activity_stage_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON activity_stage
  FOR EACH ROW EXECUTE FUNCTION reject_published_activity_config_mutation();

CREATE OR REPLACE FUNCTION reject_activity_version_mutation()
RETURNS trigger AS $$
BEGIN
  IF OLD.published_at IS NOT NULL THEN
    RAISE EXCEPTION 'published activity version is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_version_immutable ON activity_version;
CREATE TRIGGER trg_activity_version_immutable
  BEFORE UPDATE OR DELETE ON activity_version
  FOR EACH ROW EXECUTE FUNCTION reject_activity_version_mutation();

CREATE OR REPLACE FUNCTION reject_activity_append_only_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% is append-only; write a compensating record instead', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_reward_grant_ledger_immutable ON reward_grant_ledger;
CREATE TRIGGER trg_reward_grant_ledger_immutable
  BEFORE UPDATE OR DELETE ON reward_grant_ledger
  FOR EACH ROW EXECUTE FUNCTION reject_activity_append_only_mutation();
DROP TRIGGER IF EXISTS trg_reward_grant_ledger_no_truncate ON reward_grant_ledger;
CREATE TRIGGER trg_reward_grant_ledger_no_truncate
  BEFORE TRUNCATE ON reward_grant_ledger
  FOR EACH STATEMENT EXECUTE FUNCTION reject_activity_append_only_mutation();
DROP TRIGGER IF EXISTS trg_activity_audit_log_immutable ON activity_audit_log;
CREATE TRIGGER trg_activity_audit_log_immutable
  BEFORE UPDATE OR DELETE ON activity_audit_log
  FOR EACH ROW EXECUTE FUNCTION reject_activity_append_only_mutation();
DROP TRIGGER IF EXISTS trg_activity_audit_log_no_truncate ON activity_audit_log;
CREATE TRIGGER trg_activity_audit_log_no_truncate
  BEFORE TRUNCATE ON activity_audit_log
  FOR EACH STATEMENT EXECUTE FUNCTION reject_activity_append_only_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON reward_grant_ledger FROM PUBLIC;
REVOKE UPDATE, DELETE, TRUNCATE ON activity_audit_log FROM PUBLIC;
