-- Logical owner: game-server
-- Compatibility phase: expand
-- Irreversible risk: none for a new empty database; initialized databases must use the catalog baseline workflow.
-- Baseline schema extracted from db/init.sql. This file contains schema only; development data belongs in db/seeds/development.
CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = current_timestamp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS game_connection_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL CHECK (session_id >= 0),
  player_id varchar(64) NULL,
  account_player_id varchar(64) NULL,
  character_id varchar(64) NULL,
  peer_addr varchar(128) NULL,
  event_type varchar(32) NOT NULL,
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_player_id
  ON game_connection_audit_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_account_player_id
  ON game_connection_audit_logs (account_player_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_character_id
  ON game_connection_audit_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_event_type
  ON game_connection_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_game_connection_audit_logs_created_at
  ON game_connection_audit_logs (created_at);

CREATE TABLE IF NOT EXISTS room_event_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id varchar(64) NOT NULL,
  room_subject_id varchar(64) NULL,
  player_id varchar(64) NULL,
  account_player_id varchar(64) NULL,
  character_id varchar(64) NULL,
  owner_player_id varchar(64) NULL,
  owner_character_id varchar(64) NULL,
  event_type varchar(32) NOT NULL,
  room_state varchar(32) NULL,
  member_count integer NOT NULL DEFAULT 0 CHECK (member_count >= 0),
  details_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_id
  ON room_event_logs (room_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_room_subject_id
  ON room_event_logs (room_subject_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_player_id
  ON room_event_logs (player_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_account_player_id
  ON room_event_logs (account_player_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_character_id
  ON room_event_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_owner_character_id
  ON room_event_logs (owner_character_id);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_event_type
  ON room_event_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_room_event_logs_created_at
  ON room_event_logs (created_at);

CREATE TABLE IF NOT EXISTS metrics_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name varchar(64) NOT NULL,
  bucket_time integer NOT NULL CHECK (bucket_time >= 0),
  qps integer NOT NULL DEFAULT 0 CHECK (qps >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  online_value integer NOT NULL DEFAULT 0 CHECK (online_value >= 0),
  extra jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

COMMENT ON COLUMN metrics_archive.bucket_time IS '5-second bucket unix timestamp in seconds';
COMMENT ON COLUMN metrics_archive.online_value IS 'online_sessions / online_players / connections, etc.';
COMMENT ON COLUMN metrics_archive.extra IS 'service specific fields';

CREATE INDEX IF NOT EXISTS idx_metrics_archive_service_time
  ON metrics_archive (service_name, bucket_time);

CREATE TABLE IF NOT EXISTS characters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  account_player_id varchar(64) NOT NULL,
  world_id bigint NOT NULL DEFAULT 0,
  name varchar(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'active',
  appearance_json jsonb NOT NULL,
  scene_id integer NOT NULL,
  x real NOT NULL DEFAULT 0,
  y real NOT NULL DEFAULT 0,
  dir_x real NOT NULL DEFAULT 0,
  dir_y real NOT NULL DEFAULT 1,
  affinity_earth integer NOT NULL DEFAULT 2500,
  affinity_fire integer NOT NULL DEFAULT 2500,
  affinity_water integer NOT NULL DEFAULT 2500,
  affinity_wind integer NOT NULL DEFAULT 2500,
  mastery_earth integer NOT NULL DEFAULT 0,
  mastery_fire integer NOT NULL DEFAULT 0,
  mastery_water integer NOT NULL DEFAULT 0,
  mastery_wind integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  last_login_at timestamptz NULL,
  deleted_at timestamptz NULL,
  CONSTRAINT uk_characters_character_id UNIQUE (character_id),
  CONSTRAINT ck_characters_affinity_non_negative CHECK (
    affinity_earth >= 0
    AND affinity_fire >= 0
    AND affinity_water >= 0
    AND affinity_wind >= 0
  ),
  CONSTRAINT ck_characters_affinity_total CHECK (
    affinity_earth + affinity_fire + affinity_water + affinity_wind = 10000
  ),
  CONSTRAINT ck_characters_mastery_non_negative CHECK (
    mastery_earth >= 0
    AND mastery_fire >= 0
    AND mastery_water >= 0
    AND mastery_wind >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_characters_account_player_id
  ON characters (account_player_id);
CREATE INDEX IF NOT EXISTS idx_characters_world_id
  ON characters (world_id);
CREATE INDEX IF NOT EXISTS idx_characters_status
  ON characters (status);
CREATE INDEX IF NOT EXISTS idx_characters_created_at
  ON characters (created_at);

CREATE TABLE IF NOT EXISTS character_element_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  source_type varchar(32) NOT NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  affinity_earth_delta integer NOT NULL DEFAULT 0,
  affinity_fire_delta integer NOT NULL DEFAULT 0,
  affinity_water_delta integer NOT NULL DEFAULT 0,
  affinity_wind_delta integer NOT NULL DEFAULT 0,
  mastery_earth_delta integer NOT NULL DEFAULT 0,
  mastery_fire_delta integer NOT NULL DEFAULT 0,
  mastery_water_delta integer NOT NULL DEFAULT 0,
  mastery_wind_delta integer NOT NULL DEFAULT 0,
  before_json jsonb NOT NULL,
  after_json jsonb NOT NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_element_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_element_logs_character_id
  ON character_element_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_created_at_desc
  ON character_element_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_character_created_at_desc
  ON character_element_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_element_logs_source
  ON character_element_logs (source_type, source_id);

CREATE TABLE IF NOT EXISTS character_disciplines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  discipline_id varchar(64) NOT NULL,
  points bigint NOT NULL DEFAULT 0 CHECK (points >= 0),
  tier varchar(32) NOT NULL DEFAULT 'novice',
  active boolean NOT NULL DEFAULT false,
  learned_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_disciplines_discipline UNIQUE (character_id, discipline_id),
  CONSTRAINT fk_character_disciplines_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_disciplines_character_id
  ON character_disciplines (character_id);
CREATE INDEX IF NOT EXISTS idx_character_disciplines_character_active
  ON character_disciplines (character_id, active);
CREATE INDEX IF NOT EXISTS idx_character_disciplines_updated_at
  ON character_disciplines (updated_at);

DROP TRIGGER IF EXISTS trg_character_disciplines_updated_at ON character_disciplines;
CREATE TRIGGER trg_character_disciplines_updated_at
  BEFORE UPDATE ON character_disciplines
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_discipline_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  discipline_id varchar(64) NOT NULL,
  action varchar(32) NOT NULL,
  source_type varchar(32) NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  before_json jsonb NULL,
  after_json jsonb NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_discipline_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_character_id
  ON character_discipline_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_created_at_desc
  ON character_discipline_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_character_created_at_desc
  ON character_discipline_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_discipline_id
  ON character_discipline_logs (discipline_id);
CREATE INDEX IF NOT EXISTS idx_character_discipline_logs_source
  ON character_discipline_logs (source_type, source_id);

CREATE TABLE IF NOT EXISTS character_titles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  title_id varchar(64) NOT NULL,
  source_type varchar(32) NOT NULL,
  source_id varchar(128) NULL,
  is_equipped boolean NOT NULL DEFAULT false,
  unlocked_at timestamptz NOT NULL DEFAULT current_timestamp,
  expires_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_titles_title UNIQUE (character_id, title_id),
  CONSTRAINT fk_character_titles_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

COMMENT ON TABLE character_titles IS
  'A character owns many titles. Equip only one main display title by service transaction: unequip old title, then equip the new title; avoid partial unique indexes for cross-database compatibility.';

CREATE INDEX IF NOT EXISTS idx_character_titles_character_id
  ON character_titles (character_id);
CREATE INDEX IF NOT EXISTS idx_character_titles_character_equipped
  ON character_titles (character_id, is_equipped);
CREATE INDEX IF NOT EXISTS idx_character_titles_is_equipped
  ON character_titles (is_equipped);
CREATE INDEX IF NOT EXISTS idx_character_titles_expires_at
  ON character_titles (expires_at);

DROP TRIGGER IF EXISTS trg_character_titles_updated_at ON character_titles;
CREATE TRIGGER trg_character_titles_updated_at
  BEFORE UPDATE ON character_titles
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_title_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  title_id varchar(64) NOT NULL,
  action varchar(32) NOT NULL,
  source_type varchar(32) NULL,
  source_id varchar(128) NULL,
  operator_type varchar(32) NULL,
  operator_id varchar(128) NULL,
  before_json jsonb NULL,
  after_json jsonb NULL,
  reason varchar(255) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT fk_character_title_logs_character_id
    FOREIGN KEY (character_id) REFERENCES characters(character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_title_logs_character_id
  ON character_title_logs (character_id);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_created_at_desc
  ON character_title_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_character_created_at_desc
  ON character_title_logs (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_title_logs_title_id
  ON character_title_logs (title_id);

CREATE TABLE IF NOT EXISTS character_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id varchar(64) NOT NULL,
  hp bigint NOT NULL DEFAULT 0,
  inventory_data jsonb NOT NULL,
  warehouse_data jsonb NOT NULL,
  equipment_data jsonb NOT NULL,
  attr_base_data jsonb NOT NULL,
  visual_data jsonb NOT NULL,
  buffs_data jsonb NOT NULL,
  progress_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  asset_revision bigint NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_inventory_character_id UNIQUE (character_id)
);

CREATE INDEX IF NOT EXISTS idx_character_inventory_updated_at
  ON character_inventory (updated_at);

DROP TRIGGER IF EXISTS trg_character_inventory_updated_at ON character_inventory;
CREATE TRIGGER trg_character_inventory_updated_at
  BEFORE UPDATE ON character_inventory
  FOR EACH ROW
  EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE IF NOT EXISTS character_inventory_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  source varchar(64) NOT NULL,
  items_json jsonb NOT NULL,
  reason varchar(512) NULL,
  request_fingerprint varchar(71) NOT NULL,
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_inventory_grants_request_id UNIQUE (request_id),
  CONSTRAINT chk_character_inventory_grants_fingerprint
    CHECK (request_fingerprint ~ '^sha256:[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_character_inventory_grants_character_id
  ON character_inventory_grants (character_id);

CREATE TABLE IF NOT EXISTS character_asset_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  request_fingerprint varchar(71) NOT NULL,
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_character_asset_requests_request_id UNIQUE (request_id)
);

CREATE INDEX IF NOT EXISTS idx_character_asset_requests_character_id
  ON character_asset_requests (character_id);

CREATE TABLE IF NOT EXISTS character_asset_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  request_fingerprint varchar(71) NOT NULL,
  asset_type varchar(32) NOT NULL,
  item_id integer NOT NULL,
  binding_json jsonb NOT NULL,
  quantity_before bigint NOT NULL,
  quantity_after bigint NOT NULL,
  quantity_delta bigint NOT NULL,
  container varchar(32) NOT NULL,
  source varchar(64) NOT NULL,
  reason varchar(512) NOT NULL,
  snapshot_revision bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT chk_character_asset_ledger_nonzero_delta CHECK (quantity_delta <> 0)
);

CREATE INDEX IF NOT EXISTS idx_character_asset_ledger_character_created_at
  ON character_asset_ledger (character_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_asset_ledger_request_id
  ON character_asset_ledger (request_id);

-- Asset ledger rows are append-only evidence.  New columns are additive so existing grant
-- history stays queryable during a rolling upgrade; legacy rows retain explicit legacy values.
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS origin_type varchar(32) NOT NULL DEFAULT 'legacy';
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS origin_id varchar(128) NOT NULL DEFAULT '';
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS delivery_method varchar(32) NOT NULL DEFAULT 'direct';
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS delivery_id varchar(128) NULL;
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS mail_id varchar(64) NULL;
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS fallback_reason varchar(64) NULL;
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS rule_version varchar(256) NOT NULL DEFAULT 'legacy-unversioned';
ALTER TABLE character_asset_ledger
  ADD COLUMN IF NOT EXISTS operator_id varchar(128) NULL;

CREATE INDEX IF NOT EXISTS idx_character_asset_ledger_origin_created_at
  ON character_asset_ledger (origin_type, origin_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_character_asset_ledger_delivery_id
  ON character_asset_ledger (delivery_id);
CREATE INDEX IF NOT EXISTS idx_character_asset_ledger_mail_id
  ON character_asset_ledger (mail_id);

CREATE OR REPLACE FUNCTION reject_character_asset_ledger_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'character_asset_ledger is append-only; write a compensating asset transaction instead';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_character_asset_ledger_immutable_row ON character_asset_ledger;
CREATE TRIGGER trg_character_asset_ledger_immutable_row
BEFORE UPDATE OR DELETE ON character_asset_ledger
FOR EACH ROW EXECUTE FUNCTION reject_character_asset_ledger_mutation();

DROP TRIGGER IF EXISTS trg_character_asset_ledger_immutable_truncate ON character_asset_ledger;
CREATE TRIGGER trg_character_asset_ledger_immutable_truncate
BEFORE TRUNCATE ON character_asset_ledger
FOR EACH STATEMENT EXECUTE FUNCTION reject_character_asset_ledger_mutation();

-- Reward delivery keeps the direct/mail decision separate from the inventory request record.
-- A pending row is a durable mail-service creation intent; later workflow stages consume it.
CREATE TABLE IF NOT EXISTS reward_delivery_records (
  request_id varchar(128) PRIMARY KEY,
  character_id varchar(128) NOT NULL,
  request_fingerprint varchar(71) NOT NULL,
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_reward_delivery_records_character_id
  ON reward_delivery_records (character_id, created_at DESC);

CREATE TABLE IF NOT EXISTS reward_mail_outbox (
  delivery_request_id varchar(128) PRIMARY KEY,
  reward_request_id varchar(128) NOT NULL,
  mail_id varchar(64) NOT NULL,
  character_id varchar(128) NOT NULL,
  request_fingerprint varchar(71) NOT NULL,
  origin_type varchar(32) NOT NULL,
  origin_id varchar(128) NOT NULL,
  delivery_policy varchar(32) NOT NULL,
  items_json jsonb NOT NULL,
  reason varchar(512) NOT NULL,
  operator_json jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_reward_mail_outbox_reward_request UNIQUE (reward_request_id),
  CONSTRAINT uk_reward_mail_outbox_mail_id UNIQUE (mail_id)
);

ALTER TABLE reward_mail_outbox
  ADD COLUMN IF NOT EXISTS delivery_policy varchar(32) NOT NULL DEFAULT 'MAIL_ONLY';

CREATE INDEX IF NOT EXISTS idx_reward_mail_outbox_pending
  ON reward_mail_outbox (status, created_at);
CREATE INDEX IF NOT EXISTS idx_reward_mail_outbox_character_id
  ON reward_mail_outbox (character_id, created_at DESC);
