-- Mail Service Database Schema
-- Database: myserver_mail

CREATE TABLE IF NOT EXISTS mails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  sender_type varchar(32) NOT NULL DEFAULT 'system',
  sender_id varchar(64) NOT NULL,
  sender_name varchar(128) NULL,
  from_player_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  title varchar(256) NOT NULL,
  content text NULL,
  attachments jsonb NULL,
  mail_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_id varchar(64) NULL,
  created_by_name varchar(128) NULL,
  status varchar(32) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  read_at timestamptz NULL,
  claimed_at timestamptz NULL,
  expires_at timestamptz NULL,
  CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
);

CREATE INDEX IF NOT EXISTS idx_mails_to_player_id
  ON mails (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mails_status
  ON mails (to_player_id, status);
CREATE INDEX IF NOT EXISTS idx_mails_created_at
  ON mails (created_at);

CREATE TABLE IF NOT EXISTS mail_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz NULL DEFAULT current_timestamp,
  locked_until timestamptz NULL,
  last_error varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  sent_at timestamptz NULL,
  CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
  CONSTRAINT fk_mail_notification_outbox_mail_id
    FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
  ON mail_notification_outbox (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
  ON mail_notification_outbox (to_player_id);

-- Sample data for testing
INSERT INTO mails (
  mail_id,
  sender_type,
  sender_id,
  sender_name,
  from_player_id,
  to_player_id,
  title,
  content,
  mail_type,
  created_by_type,
  created_by_id,
  created_by_name,
  status
)
VALUES
  ('mail_test_001', 'system', 'system', '系统', 'system', 'player_001', 'Welcome to MyServer', 'Welcome to the game!', 'system', 'system', 'system', '系统', 'unread'),
  ('mail_test_002', 'system', 'system', '系统', 'system', 'player_001', 'GM Notice', 'Server maintenance at 2:00 AM.', 'notice', 'admin', 'gm001', 'GM 001', 'unread')
ON CONFLICT (mail_id) DO NOTHING;
