-- Mail Service Database Schema
-- Database: myserver_mail

CREATE TABLE IF NOT EXISTS mails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  sender_type varchar(32) NOT NULL DEFAULT 'system',
  sender_id varchar(64) NOT NULL,
  sender_name varchar(128) NULL,
  from_player_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  title varchar(256) NOT NULL,
  content text NULL,
  attachments jsonb NULL,
  mail_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_id varchar(64) NULL,
  created_by_name varchar(128) NULL,
  delivery_request_id varchar(128) NULL,
  delivery_character_id varchar(64) NULL,
  delivery_fingerprint varchar(71) NULL,
  origin_type varchar(32) NULL,
  origin_id varchar(128) NULL,
  delivery_policy varchar(32) NULL,
  operator_json jsonb NULL,
  status varchar(32) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  read_at timestamptz NULL,
  claimed_at timestamptz NULL,
  expires_at timestamptz NULL,
  CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
);

CREATE INDEX IF NOT EXISTS idx_mails_to_player_id
  ON mails (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mails_status
  ON mails (to_player_id, status);
CREATE INDEX IF NOT EXISTS idx_mails_created_at
  ON mails (created_at);

-- Reward mails are created only through the service-to-service delivery endpoint. Keep legacy
-- mails nullable for rolling upgrades, while making a delivery request immutable and unique.
ALTER TABLE mails ADD COLUMN IF NOT EXISTS delivery_request_id varchar(128) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS delivery_character_id varchar(64) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS delivery_fingerprint varchar(71) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS origin_type varchar(32) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS origin_id varchar(128) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS delivery_policy varchar(32) NULL;
ALTER TABLE mails ADD COLUMN IF NOT EXISTS operator_json jsonb NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_mails_delivery_request_id
  ON mails (delivery_request_id) WHERE delivery_request_id IS NOT NULL;
ALTER TABLE mails DROP CONSTRAINT IF EXISTS ck_mails_reward_delivery_metadata;
ALTER TABLE mails ADD CONSTRAINT ck_mails_reward_delivery_metadata CHECK (
  delivery_request_id IS NULL OR (
    delivery_fingerprint ~ '^sha256:[0-9a-f]{64}$'
    AND delivery_character_id IS NOT NULL
    AND origin_type IS NOT NULL
    AND origin_id IS NOT NULL
    AND delivery_policy = 'MAIL_ONLY'
    AND operator_json IS NOT NULL
    AND jsonb_typeof(operator_json) = 'object'
  )
);

CREATE TABLE IF NOT EXISTS mail_claim_workflows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  player_id varchar(64) NOT NULL,
  claim_request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  attachments_snapshot jsonb NOT NULL,
  attachments_fingerprint varchar(71) NOT NULL,
  grant_contract_version smallint NOT NULL DEFAULT 1,
  status varchar(32) NOT NULL,
  attempts integer NOT NULL DEFAULT 1 CHECK (attempts > 0),
  lease_owner varchar(128) NULL,
  lease_token varchar(64) NULL,
  lease_expires_at timestamptz NULL,
  last_trace_id varchar(32) NULL,
  last_error_code varchar(128) NULL,
  last_error_category varchar(64) NULL,
  last_result_state varchar(32) NULL,
  last_error_retryable boolean NULL,
  last_error_message varchar(512) NULL,
  result_summary jsonb NULL,
  game_instance_id varchar(128) NULL,
  recovery_attempts integer NOT NULL DEFAULT 0 CHECK (recovery_attempts >= 0),
  next_recovery_at timestamptz NULL DEFAULT current_timestamp,
  recovery_mode varchar(16) NULL,
  recovery_lease_owner varchar(128) NULL,
  recovery_lease_token varchar(64) NULL,
  recovery_lease_expires_at timestamptz NULL,
  recovery_started_at timestamptz NULL,
  last_recovery_at timestamptz NULL,
  last_query_status varchar(32) NULL,
  last_query_fingerprint varchar(71) NULL,
  last_query_error_code varchar(128) NULL,
  last_query_result_state varchar(32) NULL,
  last_query_instance_ids jsonb NULL,
  manual_review_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  completed_at timestamptz NULL,
  CONSTRAINT uk_mail_claim_workflows_mail_id UNIQUE (mail_id),
  CONSTRAINT uk_mail_claim_workflows_request_id UNIQUE (claim_request_id),
  CONSTRAINT ck_mail_claim_workflows_status CHECK (
    status IN ('processing', 'retryable_failure', 'permanent_failure', 'reconciliation_pending', 'manual_review', 'claimed')
  ),
  CONSTRAINT ck_mail_claim_workflows_snapshot CHECK (jsonb_typeof(attachments_snapshot) = 'array'),
  CONSTRAINT ck_mail_claim_workflows_fingerprint CHECK (attachments_fingerprint ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT ck_mail_claim_workflows_lease CHECK (
    (status = 'processing' AND lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)
    OR
    (status <> 'processing' AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL)
  ),
  CONSTRAINT ck_mail_claim_workflows_recovery_lease CHECK (
    (recovery_mode IS NULL AND recovery_lease_owner IS NULL AND recovery_lease_token IS NULL AND recovery_lease_expires_at IS NULL)
    OR
    (recovery_mode IS NOT NULL AND recovery_lease_owner IS NOT NULL AND recovery_lease_token IS NOT NULL AND recovery_lease_expires_at IS NOT NULL)
  ),
  CONSTRAINT ck_mail_claim_workflows_recovery_mode CHECK (
    recovery_mode IS NULL OR recovery_mode IN ('query', 'grant')
  )
);

-- Existing v1 rows receive the default. Roll back application binaries before removing this
-- column or the expanded status constraint; older binaries ignore the additive column.
ALTER TABLE mail_claim_workflows
  ADD COLUMN IF NOT EXISTS grant_contract_version smallint NOT NULL DEFAULT 1;
ALTER TABLE mail_claim_workflows DROP CONSTRAINT IF EXISTS ck_mail_claim_workflows_status;
ALTER TABLE mail_claim_workflows ADD CONSTRAINT ck_mail_claim_workflows_status CHECK (
  status IN ('processing', 'retryable_failure', 'blocked_capacity', 'permanent_failure', 'reconciliation_pending', 'manual_review', 'claimed')
);
ALTER TABLE mail_claim_workflows DROP CONSTRAINT IF EXISTS ck_mail_claim_workflows_contract_version;
ALTER TABLE mail_claim_workflows ADD CONSTRAINT ck_mail_claim_workflows_contract_version CHECK (
  grant_contract_version = 1
);

CREATE INDEX IF NOT EXISTS idx_mail_claim_workflows_recovery
  ON mail_claim_workflows (status, next_recovery_at, recovery_lease_expires_at, lease_expires_at);
CREATE INDEX IF NOT EXISTS idx_mail_claim_workflows_player
  ON mail_claim_workflows (player_id, updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_mail_claim_workflows_recovery_lease_token
  ON mail_claim_workflows (recovery_lease_token)
  WHERE recovery_lease_token IS NOT NULL;

CREATE TABLE IF NOT EXISTS mail_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  event_id varchar(128) NOT NULL,
  event_version smallint NOT NULL DEFAULT 1,
  trace_id varchar(32) NOT NULL,
  occurred_at bigint NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts integer NOT NULL DEFAULT 8 CHECK (max_attempts > 0),
  next_attempt_at timestamptz NULL DEFAULT current_timestamp,
  locked_until timestamptz NULL,
  lease_owner varchar(128) NULL,
  lease_token varchar(64) NULL,
  last_error varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  sent_at timestamptz NULL,
  terminal_at timestamptz NULL,
  CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
  CONSTRAINT uk_mail_notification_outbox_event_id UNIQUE (event_id),
  CONSTRAINT fk_mail_notification_outbox_mail_id
    FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
  ON mail_notification_outbox (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
  ON mail_notification_outbox (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_retention
  ON mail_notification_outbox (status, sent_at, terminal_at);

CREATE TABLE IF NOT EXISTS mail_admin_operation_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_request_id varchar(128) NOT NULL,
  action varchar(64) NOT NULL,
  target_type varchar(64) NOT NULL,
  target_value varchar(128) NOT NULL,
  actor varchar(128) NOT NULL,
  reason varchar(512) NOT NULL,
  high_risk boolean NOT NULL DEFAULT false,
  before_snapshot jsonb NOT NULL,
  after_snapshot jsonb NOT NULL,
  result jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT uk_mail_admin_operation_request UNIQUE (operation_request_id),
  CONSTRAINT ck_mail_admin_operation_snapshots CHECK (
    jsonb_typeof(before_snapshot) = 'object'
    AND jsonb_typeof(after_snapshot) = 'object'
    AND jsonb_typeof(result) = 'object'
  )
);

CREATE INDEX IF NOT EXISTS idx_mail_admin_operation_target
  ON mail_admin_operation_audit (target_type, target_value, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mail_admin_operation_actor
  ON mail_admin_operation_audit (actor, created_at DESC);

CREATE OR REPLACE FUNCTION reject_mail_admin_operation_audit_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'mail_admin_operation_audit is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_mail_admin_operation_audit_immutable ON mail_admin_operation_audit;
CREATE TRIGGER trg_mail_admin_operation_audit_immutable
  BEFORE UPDATE OR DELETE ON mail_admin_operation_audit
  FOR EACH ROW EXECUTE FUNCTION reject_mail_admin_operation_audit_mutation();

DROP TRIGGER IF EXISTS trg_mail_admin_operation_audit_no_truncate ON mail_admin_operation_audit;
CREATE TRIGGER trg_mail_admin_operation_audit_no_truncate
  BEFORE TRUNCATE ON mail_admin_operation_audit
  FOR EACH STATEMENT EXECUTE FUNCTION reject_mail_admin_operation_audit_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON mail_admin_operation_audit FROM PUBLIC;
