-- Mail Service Database Schema
-- Database: myserver_mail

CREATE TABLE IF NOT EXISTS mails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  sender_type varchar(32) NOT NULL DEFAULT 'system',
  sender_id varchar(64) NOT NULL,
  sender_name varchar(128) NULL,
  from_player_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  title varchar(256) NOT NULL,
  content text NULL,
  attachments jsonb NULL,
  mail_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_type varchar(32) NOT NULL DEFAULT 'system',
  created_by_id varchar(64) NULL,
  created_by_name varchar(128) NULL,
  status varchar(32) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  read_at timestamptz NULL,
  claimed_at timestamptz NULL,
  expires_at timestamptz NULL,
  CONSTRAINT uk_mails_mail_id UNIQUE (mail_id)
);

CREATE INDEX IF NOT EXISTS idx_mails_to_player_id
  ON mails (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mails_status
  ON mails (to_player_id, status);
CREATE INDEX IF NOT EXISTS idx_mails_created_at
  ON mails (created_at);

CREATE TABLE IF NOT EXISTS mail_claim_workflows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  player_id varchar(64) NOT NULL,
  claim_request_id varchar(128) NOT NULL,
  character_id varchar(64) NOT NULL,
  attachments_snapshot jsonb NOT NULL,
  attachments_fingerprint varchar(71) NOT NULL,
  status varchar(32) NOT NULL,
  attempts integer NOT NULL DEFAULT 1 CHECK (attempts > 0),
  lease_owner varchar(128) NULL,
  lease_token varchar(64) NULL,
  lease_expires_at timestamptz NULL,
  last_trace_id varchar(32) NULL,
  last_error_code varchar(128) NULL,
  last_error_category varchar(64) NULL,
  last_result_state varchar(32) NULL,
  last_error_retryable boolean NULL,
  last_error_message varchar(512) NULL,
  result_summary jsonb NULL,
  game_instance_id varchar(128) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  completed_at timestamptz NULL,
  CONSTRAINT uk_mail_claim_workflows_mail_id UNIQUE (mail_id),
  CONSTRAINT uk_mail_claim_workflows_request_id UNIQUE (claim_request_id),
  CONSTRAINT ck_mail_claim_workflows_status CHECK (
    status IN ('processing', 'retryable_failure', 'permanent_failure', 'reconciliation_pending', 'claimed')
  ),
  CONSTRAINT ck_mail_claim_workflows_snapshot CHECK (jsonb_typeof(attachments_snapshot) = 'array'),
  CONSTRAINT ck_mail_claim_workflows_fingerprint CHECK (attachments_fingerprint ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT ck_mail_claim_workflows_lease CHECK (
    (status = 'processing' AND lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)
    OR
    (status <> 'processing' AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_mail_claim_workflows_recovery
  ON mail_claim_workflows (status, lease_expires_at, updated_at);
CREATE INDEX IF NOT EXISTS idx_mail_claim_workflows_player
  ON mail_claim_workflows (player_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS mail_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mail_id varchar(64) NOT NULL,
  to_player_id varchar(64) NOT NULL,
  event_id varchar(128) NOT NULL,
  event_version smallint NOT NULL DEFAULT 1,
  trace_id varchar(32) NOT NULL,
  occurred_at bigint NOT NULL,
  payload jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts integer NOT NULL DEFAULT 8 CHECK (max_attempts > 0),
  next_attempt_at timestamptz NULL DEFAULT current_timestamp,
  locked_until timestamptz NULL,
  lease_owner varchar(128) NULL,
  lease_token varchar(64) NULL,
  last_error varchar(512) NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  sent_at timestamptz NULL,
  terminal_at timestamptz NULL,
  CONSTRAINT uk_mail_notification_outbox_mail_id UNIQUE (mail_id),
  CONSTRAINT uk_mail_notification_outbox_event_id UNIQUE (event_id),
  CONSTRAINT fk_mail_notification_outbox_mail_id
    FOREIGN KEY (mail_id) REFERENCES mails (mail_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_pending
  ON mail_notification_outbox (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_to_player_id
  ON mail_notification_outbox (to_player_id);
CREATE INDEX IF NOT EXISTS idx_mail_notification_outbox_retention
  ON mail_notification_outbox (status, sent_at, terminal_at);
