// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const ITEMTABLE_SCHEMA_SIGNATURE: &str = "Id:int|Code:string|Name:string|Type:string|Quality:string|MaxStack:int|Price:int|EquipSlot:string|LevelRequired:int|BindType:string|Attack:int|Defense:int|MaxHp:int|CritRate:float|MoveSpeed:float|UseEffect:string|UseTarget:string|UseValue:int|CoolDownMs:int|Description:string";

#[derive(Debug, Clone, Default)]
pub struct ItemTableRow {
    pub id: i32,
    pub code: StringKey,
    pub name: StringKey,
    pub type_: StringKey,
    pub quality: StringKey,
    pub maxstack: i32,
    pub price: i32,
    pub equipslot: StringKey,
    pub levelrequired: i32,
    pub bindtype: StringKey,
    pub attack: i32,
    pub defense: i32,
    pub maxhp: i32,
    pub critrate: f32,
    pub movespeed: f32,
    pub useeffect: StringKey,
    pub usetarget: StringKey,
    pub usevalue: i32,
    pub cooldownms: i32,
    pub description: StringKey,
}

#[derive(Debug, Clone, Default)]
pub struct ItemTable {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<ItemTableRow>,
    pub by_id: std::collections::HashMap<i32, usize>,
}

impl CsvTableLoader for ItemTable {
    const TABLE_NAME: &'static str = "ItemTable";
    const SCHEMA_SIGNATURE: &'static str = ITEMTABLE_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(trimmed);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = ItemTableRow {
                id: reader.parse_i32(0, "Id")?,
                code: reader.parse_string_key(1, "Code", &mut string_pool)?,
                name: reader.parse_string_key(2, "Name", &mut string_pool)?,
                type_: reader.parse_string_key(3, "Type", &mut string_pool)?,
                quality: reader.parse_string_key(4, "Quality", &mut string_pool)?,
                maxstack: reader.parse_i32(5, "MaxStack")?,
                price: reader.parse_i32(6, "Price")?,
                equipslot: reader.parse_string_key(7, "EquipSlot", &mut string_pool)?,
                levelrequired: reader.parse_i32(8, "LevelRequired")?,
                bindtype: reader.parse_string_key(9, "BindType", &mut string_pool)?,
                attack: reader.parse_i32(10, "Attack")?,
                defense: reader.parse_i32(11, "Defense")?,
                maxhp: reader.parse_i32(12, "MaxHp")?,
                critrate: reader.parse_f32(13, "CritRate")?,
                movespeed: reader.parse_f32(14, "MoveSpeed")?,
                useeffect: reader.parse_string_key(15, "UseEffect", &mut string_pool)?,
                usetarget: reader.parse_string_key(16, "UseTarget", &mut string_pool)?,
                usevalue: reader.parse_i32(17, "UseValue")?,
                cooldownms: reader.parse_i32(18, "CoolDownMs")?,
                description: reader.parse_string_key(19, "Description", &mut string_pool)?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl ItemTable {
    pub fn get(&self, id: i32) -> Option<&ItemTableRow> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[ItemTableRow] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }

}

