// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const ITEMTABLE_SCHEMA_SIGNATURE: &str = "Id:int|Code:string|Name:string|Type:string|Quality:string|MaxStack:int|Price:int|EquipSlot:string|BindType:string|Attack:int|Defense:int|MaxHp:int|CritRate:float|MoveSpeed:float|TemplateElementEarth:int|TemplateElementFire:int|TemplateElementWater:int|TemplateElementWind:int|UseEffect:string|UseTarget:string|UseValue:int|UseAffinityEarthDelta:int|UseAffinityFireDelta:int|UseAffinityWaterDelta:int|UseAffinityWindDelta:int|UseMasteryEarthDelta:int|UseMasteryFireDelta:int|UseMasteryWaterDelta:int|UseMasteryWindDelta:int|CoolDownMs:int|GrowthEnabled:int|GrowthSource:string|TradeRule:string|DecomposeRule:string|InheritRule:string|DisciplineConditionKey:string|TitleUnlockSource:string|Description:string";

#[derive(Debug, Clone, Default)]
pub struct ItemTableRow {
    pub id: i32,
    pub code: StringKey,
    pub name: StringKey,
    pub type_: StringKey,
    pub quality: StringKey,
    pub maxstack: i32,
    pub price: i32,
    pub equipslot: StringKey,
    pub bindtype: StringKey,
    pub attack: i32,
    pub defense: i32,
    pub maxhp: i32,
    pub critrate: f32,
    pub movespeed: f32,
    pub templateelementearth: i32,
    pub templateelementfire: i32,
    pub templateelementwater: i32,
    pub templateelementwind: i32,
    pub useeffect: StringKey,
    pub usetarget: StringKey,
    pub usevalue: i32,
    pub useaffinityearthdelta: i32,
    pub useaffinityfiredelta: i32,
    pub useaffinitywaterdelta: i32,
    pub useaffinitywinddelta: i32,
    pub usemasteryearthdelta: i32,
    pub usemasteryfiredelta: i32,
    pub usemasterywaterdelta: i32,
    pub usemasterywinddelta: i32,
    pub cooldownms: i32,
    pub growthenabled: i32,
    pub growthsource: StringKey,
    pub traderule: StringKey,
    pub decomposerule: StringKey,
    pub inheritrule: StringKey,
    pub disciplineconditionkey: StringKey,
    pub titleunlocksource: StringKey,
    pub description: StringKey,
}

#[derive(Debug, Clone, Default)]
pub struct ItemTable {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<ItemTableRow>,
    pub by_id: std::collections::HashMap<i32, usize>,
}

impl CsvTableLoader for ItemTable {
    const TABLE_NAME: &'static str = "ItemTable";
    const SCHEMA_SIGNATURE: &'static str = ITEMTABLE_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(trimmed);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = ItemTableRow {
                id: reader.parse_i32(0, "Id")?,
                code: reader.parse_string_key(1, "Code", &mut string_pool)?,
                name: reader.parse_string_key(2, "Name", &mut string_pool)?,
                type_: reader.parse_string_key(3, "Type", &mut string_pool)?,
                quality: reader.parse_string_key(4, "Quality", &mut string_pool)?,
                maxstack: reader.parse_i32(5, "MaxStack")?,
                price: reader.parse_i32(6, "Price")?,
                equipslot: reader.parse_string_key(7, "EquipSlot", &mut string_pool)?,
                bindtype: reader.parse_string_key(8, "BindType", &mut string_pool)?,
                attack: reader.parse_i32(9, "Attack")?,
                defense: reader.parse_i32(10, "Defense")?,
                maxhp: reader.parse_i32(11, "MaxHp")?,
                critrate: reader.parse_f32(12, "CritRate")?,
                movespeed: reader.parse_f32(13, "MoveSpeed")?,
                templateelementearth: reader.parse_i32(14, "TemplateElementEarth")?,
                templateelementfire: reader.parse_i32(15, "TemplateElementFire")?,
                templateelementwater: reader.parse_i32(16, "TemplateElementWater")?,
                templateelementwind: reader.parse_i32(17, "TemplateElementWind")?,
                useeffect: reader.parse_string_key(18, "UseEffect", &mut string_pool)?,
                usetarget: reader.parse_string_key(19, "UseTarget", &mut string_pool)?,
                usevalue: reader.parse_i32(20, "UseValue")?,
                useaffinityearthdelta: reader.parse_i32(21, "UseAffinityEarthDelta")?,
                useaffinityfiredelta: reader.parse_i32(22, "UseAffinityFireDelta")?,
                useaffinitywaterdelta: reader.parse_i32(23, "UseAffinityWaterDelta")?,
                useaffinitywinddelta: reader.parse_i32(24, "UseAffinityWindDelta")?,
                usemasteryearthdelta: reader.parse_i32(25, "UseMasteryEarthDelta")?,
                usemasteryfiredelta: reader.parse_i32(26, "UseMasteryFireDelta")?,
                usemasterywaterdelta: reader.parse_i32(27, "UseMasteryWaterDelta")?,
                usemasterywinddelta: reader.parse_i32(28, "UseMasteryWindDelta")?,
                cooldownms: reader.parse_i32(29, "CoolDownMs")?,
                growthenabled: reader.parse_i32(30, "GrowthEnabled")?,
                growthsource: reader.parse_string_key(31, "GrowthSource", &mut string_pool)?,
                traderule: reader.parse_string_key(32, "TradeRule", &mut string_pool)?,
                decomposerule: reader.parse_string_key(33, "DecomposeRule", &mut string_pool)?,
                inheritrule: reader.parse_string_key(34, "InheritRule", &mut string_pool)?,
                disciplineconditionkey: reader.parse_string_key(35, "DisciplineConditionKey", &mut string_pool)?,
                titleunlocksource: reader.parse_string_key(36, "TitleUnlockSource", &mut string_pool)?,
                description: reader.parse_string_key(37, "Description", &mut string_pool)?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl ItemTable {
    pub fn get(&self, id: i32) -> Option<&ItemTableRow> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[ItemTableRow] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }
}
