// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

pub mod bufferbase;
pub mod itemtable;
pub mod scenemonsterspawn;
pub mod sceneportal;
pub mod sceneregion;
pub mod scenespawnpoint;
pub mod scenetable;
pub mod skillbase;
pub mod testtable_100;
pub mod testtable_110;
