// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

#[rustfmt::skip]
pub mod bufferbase;
#[rustfmt::skip]
pub mod characterprogresstable;
#[rustfmt::skip]
pub mod disciplinetable;
#[rustfmt::skip]
pub mod itemtable;
#[rustfmt::skip]
pub mod scenecontext;
#[rustfmt::skip]
pub mod sceneinteraction;
#[rustfmt::skip]
pub mod scenemonsterspawn;
#[rustfmt::skip]
pub mod scenenpc;
#[rustfmt::skip]
pub mod sceneportal;
#[rustfmt::skip]
pub mod sceneregion;
#[rustfmt::skip]
pub mod scenespawnpoint;
#[rustfmt::skip]
pub mod scenetable;
#[rustfmt::skip]
pub mod skillbase;
#[rustfmt::skip]
pub mod testtable_100;
#[rustfmt::skip]
pub mod testtable_110;
#[rustfmt::skip]
pub mod titletable;
