// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const SCENEPORTAL_SCHEMA_SIGNATURE: &str = "Id:int|SceneId:int|Code:string|RegionId:int|TargetSceneId:int|TargetSpawnId:int|PortalType:string|Enabled:int";

#[derive(Debug, Clone, Default)]
pub struct ScenePortalRow {
    pub id: i32,
    pub sceneid: i32,
    pub code: StringKey,
    pub regionid: i32,
    pub targetsceneid: i32,
    pub targetspawnid: i32,
    pub portaltype: StringKey,
    pub enabled: i32,
}

#[derive(Debug, Clone, Default)]
pub struct ScenePortal {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<ScenePortalRow>,
    pub by_id: std::collections::HashMap<i32, usize>,
}

impl CsvTableLoader for ScenePortal {
    const TABLE_NAME: &'static str = "ScenePortal";
    const SCHEMA_SIGNATURE: &'static str = SCENEPORTAL_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(line);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = ScenePortalRow {
                id: reader.parse_i32(0, "Id")?,
                sceneid: reader.parse_i32(1, "SceneId")?,
                code: reader.parse_string_key(2, "Code", &mut string_pool)?,
                regionid: reader.parse_i32(3, "RegionId")?,
                targetsceneid: reader.parse_i32(4, "TargetSceneId")?,
                targetspawnid: reader.parse_i32(5, "TargetSpawnId")?,
                portaltype: reader.parse_string_key(6, "PortalType", &mut string_pool)?,
                enabled: reader.parse_i32(7, "Enabled")?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl ScenePortal {
    pub fn get(&self, id: i32) -> Option<&ScenePortalRow> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[ScenePortalRow] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }

}

