// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const SCENETABLE_SCHEMA_SIGNATURE: &str = "Id:int|Code:string|Name:string|GridFile:string|Width:int|Height:int|CellSize:float|AoiBlockSize:int|DefaultSpawnId:int|Tags:Array<string>";

#[derive(Debug, Clone, Default)]
pub struct SceneTableRow {
    pub id: i32,
    pub code: StringKey,
    pub name: StringKey,
    pub gridfile: StringKey,
    pub width: i32,
    pub height: i32,
    pub cellsize: f32,
    pub aoiblocksize: i32,
    pub defaultspawnid: i32,
    pub tags: Vec<StringKey>,
}

#[derive(Debug, Clone, Default)]
pub struct SceneTable {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<SceneTableRow>,
    pub by_id: std::collections::HashMap<i32, usize>,
}

impl CsvTableLoader for SceneTable {
    const TABLE_NAME: &'static str = "SceneTable";
    const SCHEMA_SIGNATURE: &'static str = SCENETABLE_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(trimmed);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = SceneTableRow {
                id: reader.parse_i32(0, "Id")?,
                code: reader.parse_string_key(1, "Code", &mut string_pool)?,
                name: reader.parse_string_key(2, "Name", &mut string_pool)?,
                gridfile: reader.parse_string_key(3, "GridFile", &mut string_pool)?,
                width: reader.parse_i32(4, "Width")?,
                height: reader.parse_i32(5, "Height")?,
                cellsize: reader.parse_f32(6, "CellSize")?,
                aoiblocksize: reader.parse_i32(7, "AoiBlockSize")?,
                defaultspawnid: reader.parse_i32(8, "DefaultSpawnId")?,
                tags: reader.parse_string_array(9, "Tags", &mut string_pool)?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl SceneTable {
    pub fn get(&self, id: i32) -> Option<&SceneTableRow> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[SceneTableRow] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }

}

