// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const TESTTABLE_100_SCHEMA_SIGNATURE: &str = "Id:int|Field_0:Array<string>|Field_1:float|Field_2:int|Field_3:float|Field_4:Dict<string,int>|Field_5:float|Field_6:int64|Field_7:int";

#[derive(Debug, Clone, Default)]
pub struct TestTable100Row {
    pub id: i32,
    pub field_0: Vec<StringKey>,
    pub field_1: f32,
    pub field_2: i32,
    pub field_3: f32,
    pub field_4: std::collections::HashMap<StringKey, i32>,
    pub field_5: f32,
    pub field_6: i64,
    pub field_7: i32,
}

#[derive(Debug, Clone, Default)]
pub struct TestTable100 {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<TestTable100Row>,
    pub by_id: std::collections::HashMap<i32, usize>,
    pub by_field_2: std::collections::HashMap<i32, Vec<usize>>,
    pub by_field_6: std::collections::HashMap<i64, Vec<usize>>,
}

impl CsvTableLoader for TestTable100 {
    const TABLE_NAME: &'static str = "TestTable_100";
    const SCHEMA_SIGNATURE: &'static str = TESTTABLE_100_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(trimmed);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = TestTable100Row {
                id: reader.parse_i32(0, "Id")?,
                field_0: reader.parse_string_array(1, "Field_0", &mut string_pool)?,
                field_1: reader.parse_f32(2, "Field_1")?,
                field_2: reader.parse_i32(3, "Field_2")?,
                field_3: reader.parse_f32(4, "Field_3")?,
                field_4: reader.parse_string_int_dict(5, "Field_4", &mut string_pool)?,
                field_5: reader.parse_f32(6, "Field_5")?,
                field_6: reader.parse_i64(7, "Field_6")?,
                field_7: reader.parse_i32(8, "Field_7")?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.by_field_2.entry(row.field_2).or_default().push(table.rows.len());
            table.by_field_6.entry(row.field_6).or_default().push(table.rows.len());
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl TestTable100 {
    pub fn get(&self, id: i32) -> Option<&TestTable100Row> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[TestTable100Row] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }

    pub fn find_by_field_2(&self, value: i32) -> Vec<&TestTable100Row> {
        self.by_field_2
            .get(&value)
            .map(|row_indexes| {
                row_indexes
                    .iter()
                    .filter_map(|&row_index| self.rows.get(row_index))
                    .collect()
            })
            .unwrap_or_default()
    }

    pub fn find_by_field_6(&self, value: i64) -> Vec<&TestTable100Row> {
        self.by_field_6
            .get(&value)
            .map(|row_indexes| {
                row_indexes
                    .iter()
                    .filter_map(|&row_index| self.rows.get(row_index))
                    .collect()
            })
            .unwrap_or_default()
    }

}

