// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const TESTTABLE_110_SCHEMA_SIGNATURE: &str = "Id:int|Field_0:int|Field_1:string|Field_2:int|Field_3:Array<string>|Field_4:Dict<string,int>|Field_5:Array<string>";

#[derive(Debug, Clone, Default)]
pub struct TestTable110Row {
    pub id: i32,
    pub field_0: i32,
    pub field_1: StringKey,
    pub field_2: i32,
    pub field_3: Vec<StringKey>,
    pub field_4: std::collections::HashMap<StringKey, i32>,
    pub field_5: Vec<StringKey>,
}

#[derive(Debug, Clone, Default)]
pub struct TestTable110 {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<TestTable110Row>,
    pub by_id: std::collections::HashMap<i32, usize>,
    pub by_field_0: std::collections::HashMap<i32, Vec<usize>>,
}

impl CsvTableLoader for TestTable110 {
    const TABLE_NAME: &'static str = "TestTable_110";
    const SCHEMA_SIGNATURE: &'static str = TESTTABLE_110_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME)))?;
        let type_line = lines.next().ok_or_else(|| CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME)))?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!("table {} schema mismatch: expected {}, got {}", Self::TABLE_NAME, Self::SCHEMA_SIGNATURE, signature)));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(line);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} column count mismatch: expected {}, got {}", Self::TABLE_NAME, row_offset + 3, header_columns.len(), columns.len())));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = TestTable110Row {
                id: reader.parse_i32(0, "Id")?,
                field_0: reader.parse_i32(1, "Field_0")?,
                field_1: reader.parse_string_key(2, "Field_1", &mut string_pool)?,
                field_2: reader.parse_i32(3, "Field_2")?,
                field_3: reader.parse_string_array(4, "Field_3", &mut string_pool)?,
                field_4: reader.parse_string_int_dict(5, "Field_4", &mut string_pool)?,
                field_5: reader.parse_string_array(6, "Field_5", &mut string_pool)?,
            };

            if table.by_id.insert(row.id, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!("table {} row {} duplicate id {}", Self::TABLE_NAME, row_offset + 3, row.id)));
            }
            table.by_field_0.entry(row.field_0).or_default().push(table.rows.len());
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl TestTable110 {
    pub fn get(&self, id: i32) -> Option<&TestTable110Row> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[TestTable110Row] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }

    pub fn find_by_field_0(&self, value: i32) -> Vec<&TestTable110Row> {
        self.by_field_0
            .get(&value)
            .map(|row_indexes| {
                row_indexes
                    .iter()
                    .filter_map(|&row_index| self.rows.get(row_index))
                    .collect()
            })
            .unwrap_or_default()
    }

}

