// @generated by apps/game-server/tools/csv_codegen.rs
// This file is generated at compile time. Do not edit manually.

use crate::config_table::{CsvLoadError, CsvRowReader, CsvTableLoader, StringPoolBuilder};

pub type StringKey = u32;

pub const TITLETABLE_SCHEMA_SIGNATURE: &str = "TitleId:int|Name:string|Description:string|TitleType:string|SourceDomainId:string|TierRequired:string|UnlockRules:string|Effects:string|Rarity:string|Icon:string|Color:string|Tags:Array<string>|Hidden:int|Limited:int|SortOrder:int";

#[derive(Debug, Clone, Default)]
pub struct TitleTableRow {
    pub titleid: i32,
    pub name: StringKey,
    pub description: StringKey,
    pub titletype: StringKey,
    pub sourcedomainid: StringKey,
    pub tierrequired: StringKey,
    pub unlockrules: StringKey,
    pub effects: StringKey,
    pub rarity: StringKey,
    pub icon: StringKey,
    pub color: StringKey,
    pub tags: Vec<StringKey>,
    pub hidden: i32,
    pub limited: i32,
    pub sortorder: i32,
}

#[derive(Debug, Clone, Default)]
pub struct TitleTable {
    pub string_pool: std::collections::HashMap<StringKey, String>,
    pub rows: Vec<TitleTableRow>,
    pub by_id: std::collections::HashMap<i32, usize>,
}

impl CsvTableLoader for TitleTable {
    const TABLE_NAME: &'static str = "TitleTable";
    const SCHEMA_SIGNATURE: &'static str = TITLETABLE_SCHEMA_SIGNATURE;

    fn load_from_csv(path: &std::path::Path) -> Result<Self, CsvLoadError> {
        let contents = std::fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let header_line = lines.next().ok_or_else(|| {
            CsvLoadError::InvalidSchema(format!("table {} missing header line", Self::TABLE_NAME))
        })?;
        let type_line = lines.next().ok_or_else(|| {
            CsvLoadError::InvalidSchema(format!("table {} missing type line", Self::TABLE_NAME))
        })?;
        let header_columns = crate::config_table::parse_csv_columns(header_line);
        let type_columns = crate::config_table::parse_csv_columns(type_line);
        let signature = crate::config_table::schema_signature(&header_columns, &type_columns);
        if signature != Self::SCHEMA_SIGNATURE {
            return Err(CsvLoadError::InvalidSchema(format!(
                "table {} schema mismatch: expected {}, got {}",
                Self::TABLE_NAME,
                Self::SCHEMA_SIGNATURE,
                signature
            )));
        }

        let mut table = Self::default();
        let mut string_pool = StringPoolBuilder::default();

        for (row_offset, line) in lines.enumerate() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let columns = crate::config_table::parse_csv_columns(trimmed);
            if columns.len() != header_columns.len() {
                return Err(CsvLoadError::InvalidRow(format!(
                    "table {} row {} column count mismatch: expected {}, got {}",
                    Self::TABLE_NAME,
                    row_offset + 3,
                    header_columns.len(),
                    columns.len()
                )));
            }
            let reader = CsvRowReader::new(Self::TABLE_NAME, row_offset + 3, &columns);
            let row = TitleTableRow {
                titleid: reader.parse_i32(0, "TitleId")?,
                name: reader.parse_string_key(1, "Name", &mut string_pool)?,
                description: reader.parse_string_key(2, "Description", &mut string_pool)?,
                titletype: reader.parse_string_key(3, "TitleType", &mut string_pool)?,
                sourcedomainid: reader.parse_string_key(4, "SourceDomainId", &mut string_pool)?,
                tierrequired: reader.parse_string_key(5, "TierRequired", &mut string_pool)?,
                unlockrules: reader.parse_string_key(6, "UnlockRules", &mut string_pool)?,
                effects: reader.parse_string_key(7, "Effects", &mut string_pool)?,
                rarity: reader.parse_string_key(8, "Rarity", &mut string_pool)?,
                icon: reader.parse_string_key(9, "Icon", &mut string_pool)?,
                color: reader.parse_string_key(10, "Color", &mut string_pool)?,
                tags: reader.parse_string_array(11, "Tags", &mut string_pool)?,
                hidden: reader.parse_i32(12, "Hidden")?,
                limited: reader.parse_i32(13, "Limited")?,
                sortorder: reader.parse_i32(14, "SortOrder")?,
            };

            if table.by_id.insert(row.titleid, table.rows.len()).is_some() {
                return Err(CsvLoadError::InvalidRow(format!(
                    "table {} row {} duplicate id {}",
                    Self::TABLE_NAME,
                    row_offset + 3,
                    row.titleid
                )));
            }
            table.rows.push(row);
        }

        table.string_pool = string_pool.finish();
        Ok(table)
    }
}

impl TitleTable {
    pub fn get(&self, id: i32) -> Option<&TitleTableRow> {
        self.by_id
            .get(&id)
            .and_then(|&row_index| self.rows.get(row_index))
    }

    pub fn all(&self) -> &[TitleTableRow] {
        &self.rows
    }

    pub fn resolve_string(&self, key: StringKey) -> Option<&str> {
        self.string_pool.get(&key).map(|value| value.as_str())
    }
}
